namespace eval ::crowDebugger {
	# New
	::msgcat::mcset de_de  "...abort" "...abbrechen"
	# New
	::msgcat::mcset de_de  "...ok" "...ok"
	# New
	::msgcat::mcset de_de  "Debug script is not specified or not exists.!" "Kein Skript zum debuggen angegeben oder es existiert nicht.!"
	# New
	::msgcat::mcset de_de  "Debugger already running!" "Debugger bereis gestartet!"
	# New
	::msgcat::mcset de_de  "Debugger has not started!" "Debugger ist nicht gestartet!"
	# New
	::msgcat::mcset de_de  "Error" "Fehler"
	# New
	::msgcat::mcset de_de  "Interpreter is not specified or not exists!" "Kein Interpreter angegeben oder er existiert nicht!"
	# New
	::msgcat::mcset de_de  "Loading '%s' ..." "Lade '%s' ..."
	# New
	::msgcat::mcset de_de  "Start Debugger...ok" "Starte Debugger...ok"
	# New
	::msgcat::mcset de_de  "Stop Debugger....ok" "Stoppe Debugger....ok"
	# New
	::msgcat::mcset de_de  "error" "Fehler"
}

namespace eval ::crowEditor {
	::msgcat::mcset de_de  "'%s' has been delete from the file system. Save it?" "'%s' wurde im Dateisystem gelöscht. Die aktuelle Version speichern ?"
	::msgcat::mcset de_de  "'%s' has been deleted from the file system. Save ?" "'%s' wurde im Dateisystem gelöscht. Speichern ?"
	::msgcat::mcset de_de  "'%s' has been modified. Reload file ?" "'%s' wurde verändert. Datei neu laden ?"
	::msgcat::mcset de_de  "'%s' has been modified. Save changes ?" "'%s' wurde verändert. Änderungen speichern ?"
	::msgcat::mcset de_de  "Add Block Comment"  "Block als Kommentar markieren"
	::msgcat::mcset de_de  "Backward"  "Rückwärts"
	::msgcat::mcset de_de  "Case Sensitive"  "Groß/Kleinschreibung beachten"
	::msgcat::mcset de_de  "Colors"  "Farben"
	::msgcat::mcset de_de  "Comment:" "Kommentar:"
	::msgcat::mcset de_de  "Copy"  "Kopieren"
	::msgcat::mcset de_de  "Cut"  "Ausschneiden"
	::msgcat::mcset de_de  "Cut Line"  "Zeile ausschneiden"
	::msgcat::mcset de_de  "Cut word"  "Wort ausschneiden"
	::msgcat::mcset de_de  "Default disabled"  "Standard deaktiviert"
	::msgcat::mcset de_de  "Default enabled"  "Standard aktiviert"
	::msgcat::mcset de_de  "Delete"  "Löschen"
	::msgcat::mcset de_de  "Editor Settings" "Editor Einstellungen"
	::msgcat::mcset de_de  "Exit"  "Beenden"
	::msgcat::mcset de_de  "Find"  "Suchen"
	::msgcat::mcset de_de  "Find And Replace"  "Suchen und Ersetzen"
	::msgcat::mcset de_de  "Find Next"  "Nächstes finden"
	::msgcat::mcset de_de  "Find/Replace..."  "Suchen/Ersetzen..."
	::msgcat::mcset de_de  "Indent Selection"  "Auswahl einrücken"
	::msgcat::mcset de_de  "Information"  "Informationen"
	::msgcat::mcset de_de  "Information!" "Information!"
	::msgcat::mcset de_de  "Insert Macro"  "Makro einfügen"
	::msgcat::mcset de_de  "Items"  "Objekte"
	::msgcat::mcset de_de  "Jump To"  "Spring zu"
	::msgcat::mcset de_de  "Jump To..."  "Springe zu..."
	::msgcat::mcset de_de  "Numerical:" "Numerisch:"
	::msgcat::mcset de_de  "Paste"  "Einfügen"
	::msgcat::mcset de_de  "Redo"  "Wiederholen"
	::msgcat::mcset de_de  "Regular expression"  "Regulärer Ausdruck"
	::msgcat::mcset de_de  "Remove Block Comment"  "Kommentar von Block entfernen"
	::msgcat::mcset de_de  "Repalce All"  "Alle Ersetzen"
	::msgcat::mcset de_de  "Replace"  "Ersetzen"
	::msgcat::mcset de_de  "Reset"  "Zurücksetzen"
	::msgcat::mcset de_de  "Save"  "Speichern"
	::msgcat::mcset de_de  "Save File"  "Datei speichern"
	::msgcat::mcset de_de  "Save Macro"  "Makro speichern"
	::msgcat::mcset de_de  "Save file!"  "Datei speichern!"
	::msgcat::mcset de_de  "Save success"  "Speichern erfolgreich"
	::msgcat::mcset de_de  "Select All"  "Alles auswählen"
	::msgcat::mcset de_de  "Select Line"  "Zeile auswählen"
	::msgcat::mcset de_de  "Select word"  "Wort auswählen"
	::msgcat::mcset de_de  "Set Breakpoint" "Haltepunkt setzen"
	::msgcat::mcset de_de  "String Not Found"  "Text nicht gefunden"
	::msgcat::mcset de_de  "String:" "Zeichenkette:"
	::msgcat::mcset de_de  "Syntax Highlight"  "Syntax Hervorhebung"
	::msgcat::mcset de_de  "Tab width" "Tabulatorweite"
	::msgcat::mcset de_de  "Tcl Argument:" "Tcl Argument:"
	::msgcat::mcset de_de  "Tcl Command:" "Tcl Befehl:"
	::msgcat::mcset de_de  "Tk Argument:" "Tk Argument:"
	::msgcat::mcset de_de  "Tk Command:" "Tk Befehl:"
	::msgcat::mcset de_de  "Undo"  "Rückgängig"
	::msgcat::mcset de_de  "Unindent Selection"  "Auswahl ausrücken"
	::msgcat::mcset de_de  "Unset Breakpoint" "Haltepunkt entfernen"
	::msgcat::mcset de_de  "Variable:" "Variable:"
	::msgcat::mcset de_de  "Warring!"  "Warnung!"
}

namespace eval ::crowExec {
	::msgcat::mcset de_de  "%s...Exit" "%s...wurde beendet"
	::msgcat::mcset de_de  "Error" "Fehler"
	::msgcat::mcset de_de  "Interpreter '%s' not exists" "Interpreter '%s' existiert nicht"
	::msgcat::mcset de_de  "Permission denied" "Nicht genügend Rechte vorhanden"
	::msgcat::mcset de_de  "Run %s..." "Ausführen %s..."
	::msgcat::mcset de_de  "You may not permission to execuate this file! Execuate force?" "Die Datei ist nicht als ausführbar erkennbar. Dennoch ausführen?"
}

namespace eval ::crowFileProperties {
	::msgcat::mcset de_de  "Accept" "Angenommen"
	::msgcat::mcset de_de  "Accessed:" "Zugriff:"
	::msgcat::mcset de_de  "Cancel" "Abbrechen"
	::msgcat::mcset de_de  "Changed:" "Geändert:"
	::msgcat::mcset de_de  "File Properties" "Datei Eigenschaften"
	::msgcat::mcset de_de  "General" "Allgemein"
	::msgcat::mcset de_de  "Group" "Gruppe"
	::msgcat::mcset de_de  "Location:" "Ort:"
	::msgcat::mcset de_de  "Modified:" "Verändert:"
	::msgcat::mcset de_de  "Name:" "Name:"
	::msgcat::mcset de_de  "Other" "Anders"
	::msgcat::mcset de_de  "Owner" "Eigentümer"
	::msgcat::mcset de_de  "Permissions" "Rechte"
	::msgcat::mcset de_de  "Read" "Lesbar"
	::msgcat::mcset de_de  "SID" "SID"
	::msgcat::mcset de_de  "Set GID" "Set GID"
	::msgcat::mcset de_de  "Set UID" "Set UID"
	::msgcat::mcset de_de  "Size:" "Größe:"
	::msgcat::mcset de_de  "Type:" "Typ:"
	::msgcat::mcset de_de  "Write" "Schreibbar"
	::msgcat::mcset de_de  "execute" "Ausführbar"
	::msgcat::mcset de_de  "recursive apply" "rekursiv anwenden"
}

namespace eval ::crowFileRelation {
	::msgcat::mcset de_de  "Add"  "Hinzufügen"
	::msgcat::mcset de_de  "All"  "Alle"
	::msgcat::mcset de_de  "Application"  "Anwendung"
	::msgcat::mcset de_de  "Application:" "Anwendung:"
	::msgcat::mcset de_de  "Browse..."  "Durchsuchen..."
	::msgcat::mcset de_de  "File Extension:" "Dateiendung:"
	::msgcat::mcset de_de  "File Relation Setting"  "Dateiverknüpfungen"
	::msgcat::mcset de_de  "File types"  "Dateitypen"
	::msgcat::mcset de_de  "Remove"  "Entfernen"
	::msgcat::mcset de_de  "Setting default"  "Standardeinstellung"
}

namespace eval ::crowFont {
	::msgcat::mcset de_de  "Apply"  "Übernehmen"
	::msgcat::mcset de_de  "Editor font"  "Editor Schrift"
	::msgcat::mcset de_de  "Fonts setting"  "Schriftarten"
	::msgcat::mcset de_de  "Large font"  "Große Schrift"
	::msgcat::mcset de_de  "Menu font"  "Menü Schrift"
	::msgcat::mcset de_de  "Small font"  "Kleine Schrift"
	::msgcat::mcset de_de  "normal font"  "Normale Schrift"
}

namespace eval ::crowGetDir {
	::msgcat::mcset de_de  "'%s' has been deleted from the file system!" "'%s' wurde aus dem Dateisystem gelöscht!"
	::msgcat::mcset de_de  "Cancel" "Abbrechen"
	::msgcat::mcset de_de  "Choose Direcotry" "Ordner auswählen"
	::msgcat::mcset de_de  "Choose Folder First!" "Bitte erst Ordner auswählen!"
	::msgcat::mcset de_de  "Error" "Fehler"
	::msgcat::mcset de_de  "Folder Already Exists!" "Ordner existiert bereits!"
	::msgcat::mcset de_de  "New Folder" "Neuer Ordner"
	::msgcat::mcset de_de  "Ok" "Ok"
}

namespace eval ::crowIO {
	::msgcat::mcset de_de  "Cancel"  "Abbrechen"
	::msgcat::mcset de_de  "Ok" "Ok"
	::msgcat::mcset de_de  "Wrong argument!"  "Falsches Argument!"
	::msgcat::mcset de_de  "gets" "gets"
	::msgcat::mcset de_de  "read" "read"
}

namespace eval ::crowMacro {
	::msgcat::mcset de_de  ""  ""
	::msgcat::mcset de_de  "--Delete This Folder--" "--Diesen Ordner löschen--"
	::msgcat::mcset de_de  "Are you sure you want to delete macro?"  "Wollen Sie das Makro wirklich löschen?"
	::msgcat::mcset de_de  "Browse" "Durchsuchen"
	::msgcat::mcset de_de  "Cancel"  "Abbrechen"
	::msgcat::mcset de_de  "Codes:" "Codes:"
	::msgcat::mcset de_de  "Delete"  "Löschen"
	::msgcat::mcset de_de  "Macro Name:" "Makro Name:"
	::msgcat::mcset de_de  "Ok"  "Ok"
	::msgcat::mcset de_de  "Operations"  "Operationen"
	::msgcat::mcset de_de  "Save Macro"  "Makro speichern"
	::msgcat::mcset de_de  "Save Path:" "Speicherpfad:"
	::msgcat::mcset de_de  "System Define"  "System Makros"
	::msgcat::mcset de_de  "User Define"  "Benutzer Makros"
}

namespace eval ::crowRC {
	::msgcat::mcset de_de  "Create fail!"  "Erstellen fehlgeschlagen!"
	::msgcat::mcset de_de  "Error"  "Fehler"
}

namespace eval ::crowSdx {
	::msgcat::mcset de_de  "%s Elapsed time ... %02s:%02s" "%s Benötigte Zeit ... %02s:%02s"
	::msgcat::mcset de_de  "Browse" "Durchsuchen"
	::msgcat::mcset de_de  "Building starkit ..." "Erstelle Starkit ..."
	::msgcat::mcset de_de  "Cancel" "Abbrechen"
	::msgcat::mcset de_de  "Do not compress files added to starkit" "Zum Starkit hinzugefügte Dateien nicht komprimieren"
	::msgcat::mcset de_de  "Finish." "Beendet."
	::msgcat::mcset de_de  "Move '%s' -> '%s'" "Verschiebe '%s' -> '%s'"
	::msgcat::mcset de_de  "Ok" "Ok"
	::msgcat::mcset de_de  "Options" "Optionen"
	::msgcat::mcset de_de  "SDX" "SDX"
	::msgcat::mcset de_de  "Save As.." "Speichern als.."
	::msgcat::mcset de_de  "Save to:" "Speichern nach:"
	::msgcat::mcset de_de  "Script:" "Skript:"
	::msgcat::mcset de_de  "Size = %s (KB)" "Größe = %s (KB)"
	::msgcat::mcset de_de  "Starkit runtime not exists!" "Starkit Laufzeitumgebung existiert nicht!"
	::msgcat::mcset de_de  "VFS Directory:" "VFS Ordner:"
	::msgcat::mcset de_de  "Writable" "Beschreibbar"
	::msgcat::mcset de_de  "error" "Fehler"
	::msgcat::mcset de_de  "include runtime" "Laufzeitumgebung einbinden"
}

namespace eval ::crowSyntax {
	::msgcat::mcset de_de  "Cancel" "Abbrechen"
	::msgcat::mcset de_de  "Ok" "Ok"
}

namespace eval ::crowTde {
	::msgcat::mcset de_de  "CrowTDE Start success, thanks for use ^o^" "CrowTDE wurde erfolgreich gestartet, Danke das Sie CrowTDE benutzen ^o^"
	# New
	::msgcat::mcset de_de  "Loading plugin '%s' ..." "Lade Plugin '%s' ..."
}

namespace eval ::crowThread {
	::msgcat::mcset de_de  "%s Finish" "%s Beendet"
	::msgcat::mcset de_de  "Error"  "Fehler"
	::msgcat::mcset de_de  "Interpreter '%s' not exists" "Der Interpreter '%s' existiert nicht"
	::msgcat::mcset de_de  "Permission denied" "Nicht genug Rechte vorhanden."
	::msgcat::mcset de_de  "Run %s ..." "Ausführen %s ..."
	::msgcat::mcset de_de  "You may not permission to execuate this file! Execuate force?" "Datei ist nicht als ausführbar erkennbar. Dennoch ausführen?"
}

namespace eval ::fmeDebugger {
	::msgcat::mcset de_de  "Add Watch" "Beobachtungspunkt hinzufügen"
	::msgcat::mcset de_de  "Add Watch..." "Beobachtungspunkt hinzufügen..."
	::msgcat::mcset de_de  "Breakpoints" "Haltepunkte"
	::msgcat::mcset de_de  "Change Value..." "Wert ändern..."
	::msgcat::mcset de_de  "Change value" "Wert ändern"
	::msgcat::mcset de_de  "Currently-Visible Variables" "Sichtbare Variablen"
	::msgcat::mcset de_de  "Debug" "Debuggen"
	::msgcat::mcset de_de  "Debug Default Script..." "Debug Startskript..."
	::msgcat::mcset de_de  "Debug level" "Debug Stufe"
	::msgcat::mcset de_de  "Debug..." "Debuggen..."
	::msgcat::mcset de_de  "Deep" "Hoch"
	::msgcat::mcset de_de  "Free go" "Debuggen starten"
	::msgcat::mcset de_de  "Info" "Info"
	::msgcat::mcset de_de  "Lines:" "Zeilen:"
	::msgcat::mcset de_de  "Normal" "Normal"
	::msgcat::mcset de_de  "Pause" "Pause"
	::msgcat::mcset de_de  "Position:" "Position:"
	::msgcat::mcset de_de  "Remove" "Entfernen"
	::msgcat::mcset de_de  "Remove Watch" "Beobachtungspunkt entfernen"
	::msgcat::mcset de_de  "Script:" "Skript:"
	::msgcat::mcset de_de  "Shallow" "Niedrig"
	::msgcat::mcset de_de  "Start Debugger" "Debugger starten"
	::msgcat::mcset de_de  "Step" "Einzelschritt"
	::msgcat::mcset de_de  "Stop debugging" "Debuggen beenden"
	::msgcat::mcset de_de  "View" "Ansicht"
	::msgcat::mcset de_de  "Watch Variables" "Beobachtete Variablen"
	::msgcat::mcset de_de  "Watchpoint already exists!" "Beobachtungspunkt existiert bereits!"
}

namespace eval ::fmeDocView {
	::msgcat::mcset de_de  "Collapse" "Zusammenklappen"
	::msgcat::mcset de_de  "Copy" "Kopieren"
	::msgcat::mcset de_de  "Copy %d %s" "Kopieren %d %s"
	::msgcat::mcset de_de  "Document Viewer(%s)" "Dokument Betrachter (%s)"
	::msgcat::mcset de_de  "Home" "Home"
	::msgcat::mcset de_de  "Next" "Nächste"
	::msgcat::mcset de_de  "Previous" "Vorige"
	::msgcat::mcset de_de  "Top" "Anfang"
	::msgcat::mcset de_de  "View in new window" "In neuem Fenster anzeigen"
}

namespace eval ::fmeGenericSetting {
	::msgcat::mcset de_de  "Browse..."  "Durchsuchen..."
	::msgcat::mcset de_de  "Choose Tcl interpreter"  "Tcl Interpreter auswählen"
	::msgcat::mcset de_de  "Choose Tk interpreter"  "Tk Interpreter auswählen"
	::msgcat::mcset de_de  "Create new project"  "Neues Projekt erstellen"
	::msgcat::mcset de_de  "Debug Level" "Debug Stufe"
	::msgcat::mcset de_de  "Deep" "Hoch"
	::msgcat::mcset de_de  "Do nothing"  "Nichts tun"
	::msgcat::mcset de_de  "General Settings"  "Allgemeine Einstellungen"
	::msgcat::mcset de_de  "Interpreter"  "Interpreter"
	::msgcat::mcset de_de  "Normal" "Normal"
	::msgcat::mcset de_de  "Open last edit project"  "Letztes Projekt öffnen"
	::msgcat::mcset de_de  "Shallow" "Niedrig"
	::msgcat::mcset de_de  "Show startup page"  "Startseite anzeigen"
	::msgcat::mcset de_de  "Startup"  "Start"
	::msgcat::mcset de_de  "Tcl Interpreter:" "Tcl Interpreter:"
	::msgcat::mcset de_de  "Tk Interpreter:" "Tk Interpreter:"
}

namespace eval ::fmeMenuBar {
	::msgcat::mcset de_de  "About..."  "Über..."
	::msgcat::mcset de_de  "Add %s" "Füge %s hinzu"
	::msgcat::mcset de_de  "Add Block Comment"  "Block als Kommentar markieren"
	::msgcat::mcset de_de  "Add Task"  "Aufgabe hinzufügen"
	::msgcat::mcset de_de  "Add Watch..." "Beobachtungspunkt hinzufügen..."
	::msgcat::mcset de_de  "Adjust Tab Width" "Tabulatorweite anpassen"
	::msgcat::mcset de_de  "Build ' %s ' ..." "Erstelle ' %s ' ..."
	::msgcat::mcset de_de  "Build ..." "Erstellen ..."
	::msgcat::mcset de_de  "Build Project..." "Projekt erstellen..."
	::msgcat::mcset de_de  "Close"  "Schließen"
	::msgcat::mcset de_de  "Close All"  "Alle Schließen"
	::msgcat::mcset de_de  "Close Project"  "Projekt schließen"
	::msgcat::mcset de_de  "Collapse Toolbar"  "Werkzeugleiste einklappen"
	::msgcat::mcset de_de  "Copy"  "Kopieren"
	::msgcat::mcset de_de  "Cut"  "Ausschneiden"
	::msgcat::mcset de_de  "Debug" "Debuggen"
	::msgcat::mcset de_de  "Debug Default Script..." "Debug Startskript..."
	::msgcat::mcset de_de  "Debug level" "Debug Stufe"
	::msgcat::mcset de_de  "Debug..." "Debuggen..."
	::msgcat::mcset de_de  "Deep" "Hoch"
	::msgcat::mcset de_de  "Default Disabled"  "Standardmässig deaktiviert"
	::msgcat::mcset de_de  "Default Enabled"  "Standardmässig aktiviert"
	::msgcat::mcset de_de  "Default script not exists!" "Startskript existiert nicht!"
	::msgcat::mcset de_de  "Delete"  "Löschen"
	::msgcat::mcset de_de  "Delete ' %s '" "Entferne ' %s '"
	::msgcat::mcset de_de  "Delete Completed Tasks"  "Erledigte Aufgaben entfernen"
	::msgcat::mcset de_de  "Diabled All"  "Alles deaktivieren"
	::msgcat::mcset de_de  "Disabled Current Editor"  "Aktuellen Editor deaktivieren"
	::msgcat::mcset de_de  "Edit"  "Bearbeiten"
	::msgcat::mcset de_de  "Editor Details"  "Editor"
	::msgcat::mcset de_de  "Enabled All"  "Alles aktivieren"
	::msgcat::mcset de_de  "Enabled Current Editor"  "Aktuellen Editor aktivieren"
	::msgcat::mcset de_de  "Exit"  "Beenden"
	::msgcat::mcset de_de  "Expand Toolbar"  "Werkzeugleiste ausklappen"
	::msgcat::mcset de_de  "File"  "Datei"
	::msgcat::mcset de_de  "File Relation"  "Dateiverknüpfungen"
	::msgcat::mcset de_de  "Find/Replace..."  "Suchen/Ersetzen..."
	::msgcat::mcset de_de  "Folder..."  "Ordner..."
	::msgcat::mcset de_de  "Free Go" "Debuggen starten"
	::msgcat::mcset de_de  "Help"  "Hilfe"
	::msgcat::mcset de_de  "Import..."  "Importieren..."
	::msgcat::mcset de_de  "Indent Selection"  "Auswahl einrücken"
	::msgcat::mcset de_de  "Insert Macro"  "Makro einfügen"
	::msgcat::mcset de_de  "Jump To..."  "Springe zu..."
	::msgcat::mcset de_de  "Language"  "Sprache"
	::msgcat::mcset de_de  "Locale"  "Spracheinstellungen"
	::msgcat::mcset de_de  "MP3 Directory - %s" "MP3 Ordner - %s"
	::msgcat::mcset de_de  "MP3 Player Details"  "MP3 Player Einstellungen"
	::msgcat::mcset de_de  "New"  "Neu"
	::msgcat::mcset de_de  "Next Page"  "Nächste Seite"
	::msgcat::mcset de_de  "Normal" "Normal"
	::msgcat::mcset de_de  "Open"  "Öffnen"
	::msgcat::mcset de_de  "Open File"  "Datei öffnen"
	::msgcat::mcset de_de  "Open File..."  "Datei öffnen..."
	::msgcat::mcset de_de  "Open Project..."  "Projekt öffnen..."
	::msgcat::mcset de_de  "Options"  "Optionen"
	::msgcat::mcset de_de  "Paste"  "Einfügen"
	::msgcat::mcset de_de  "Pause" "Pause"
	::msgcat::mcset de_de  "Previous Page"  "Vorherige Seite"
	::msgcat::mcset de_de  "Print..."  "Drucken..."
	::msgcat::mcset de_de  "Printer Setup*"  "Drucker einrichten*"
	::msgcat::mcset de_de  "Proc Details"  "Proc"
	::msgcat::mcset de_de  "Project"  "Projekt"
	::msgcat::mcset de_de  "Project..."  "Projekt..."
	::msgcat::mcset de_de  "Properties..."  "Eigenschaften..."
	::msgcat::mcset de_de  "Raise"  "In den Vordergrund"
	::msgcat::mcset de_de  "Recent Files"  "Zuletzt verwendete Dateien"
	::msgcat::mcset de_de  "Recent Projects"  "Zuletzt verwendete Projekte"
	::msgcat::mcset de_de  "Redo"  "Wiederholen"
	::msgcat::mcset de_de  "Refresh"  "Aktualisieren"
	::msgcat::mcset de_de  "Refresh Interval (%s ms)" "Aktualisierungsintervall (%s ms)"
	::msgcat::mcset de_de  "Remove Block Comment"  "Kommentar von Block entfernen"
	::msgcat::mcset de_de  "Run Default Script..." "Startskript ausführen..."
	::msgcat::mcset de_de  "Run..."  "Ausführen..."
	::msgcat::mcset de_de  "Save"  "Speichern"
	::msgcat::mcset de_de  "Save All"  "Alle speichern"
	::msgcat::mcset de_de  "Save As"  "Speichern als"
	::msgcat::mcset de_de  "Save As ..."  "Speichern als ..."
	::msgcat::mcset de_de  "Save Macro"  "Makro speichern"
	::msgcat::mcset de_de  "Search Files..."  "Dateien suchen..."
	::msgcat::mcset de_de  "Search In Files..."  "In Dateien suchen..."
	::msgcat::mcset de_de  "Select All"  "Alles auswählen"
	::msgcat::mcset de_de  "Set ' %s ' As Default Script" "' %s ' als Startskript wählen"
	::msgcat::mcset de_de  "Settings..."  "Einstellungen..."
	::msgcat::mcset de_de  "Shallow" "Niedrig"
	::msgcat::mcset de_de  "Show Line Number"  "Zeilennummern anzeigen"
	::msgcat::mcset de_de  "Show Syntax Helper" "Syntax Hilfe anzeigen"
	::msgcat::mcset de_de  "Step" "Einzelschritt"
	::msgcat::mcset de_de  "Stop" "Stop"
	::msgcat::mcset de_de  "Syntax Check..." "Syntax Überprüfung..."
	::msgcat::mcset de_de  "Syntax Highlight"  "Syntax Hervorhebung"
	::msgcat::mcset de_de  "Tasks"  "Aufgaben"
	# New
	::msgcat::mcset de_de  "Test" "Test"
	::msgcat::mcset de_de  "Test(W)"  "Testen(W)"
	::msgcat::mcset de_de  "The settings will apply at restart CrowTDE!"  "Diese Einstellungen werden erst nach einem Neustart von CrowTDE wirksam!"
	::msgcat::mcset de_de  "Toolbar Details"  "Werkzeugleiste"
	::msgcat::mcset de_de  "Tools(T)"  "Werkzeuge(T)"
	::msgcat::mcset de_de  "UnIndent Selection"  "Auswahl ausrücken"
	::msgcat::mcset de_de  "Undo"  "Rückgängig"
	::msgcat::mcset de_de  "Version Control*"  "Versionsverwaltung*"
	::msgcat::mcset de_de  "Window"  "Fenster"
	::msgcat::mcset de_de  "error!" "Fehler!"
	# New
	::msgcat::mcset de_de  "freewrap*" "freewrap*"
}

namespace eval ::fmeNagelfar {
	::msgcat::mcset de_de  "Choose File" "Datei auswählen"
	::msgcat::mcset de_de  "Clear" "Löschen"
	::msgcat::mcset de_de  "Do Check" "Prüfung durchführen"
	::msgcat::mcset de_de  "File:" "Datei:"
	::msgcat::mcset de_de  "Save" "Speichern"
	::msgcat::mcset de_de  "Save Output..." "Ausgabe speichern..."
	# New
	::msgcat::mcset de_de  "Select File" "Datei auswählen"
	::msgcat::mcset de_de  "Select File..." "Datei auswählen..."
}

namespace eval ::fmePlayer {
	::msgcat::mcset de_de  "MP3 Folder"  "MP3 Ordner"
	::msgcat::mcset de_de  "MP3:"  "MP3:"
	::msgcat::mcset de_de  "Vol:"  "Vol:"
}

namespace eval ::fmeProcManager {
	::msgcat::mcset de_de  "Error" "Error"
	::msgcat::mcset de_de  "Interval"  "Intervall"
	::msgcat::mcset de_de  "Please specify Tcl interpreter first!" "Bitte zuerst den Tcl Interpreter auswählen!"
	::msgcat::mcset de_de  "View"  "Anzeige"
}

namespace eval ::fmeProjectManager {
	::msgcat::mcset de_de  "%s Open" "%s ist bereits offen"
	::msgcat::mcset de_de  "'%s' already exists!" "'%s' existiert bereits!"
	::msgcat::mcset de_de  "'%s' already exists." "'%s' existiert bereits."
	::msgcat::mcset de_de  "'%s' has been deleted from the file system!" "'%s' wurde aus dem Dateisystem gelöscht!"
	::msgcat::mcset de_de  "'%s' not exists!" "'%s' existiert nicht!"
	::msgcat::mcset de_de  "All"  "Alle"
	::msgcat::mcset de_de  "Are you sure you want to delete '%s' from the file system ?" "Wollen Sie wirklich die Datei '%s' löschen ?"
	::msgcat::mcset de_de  "Build..." "Erstellen..."
	::msgcat::mcset de_de  "Cancel" "Abbrechen"
	::msgcat::mcset de_de  "Check Syntax*"  "Syntax prüfen*"
	::msgcat::mcset de_de  "Close Project"  "Projekt schließen"
	::msgcat::mcset de_de  "Confirm"  "Bestätigen"
	::msgcat::mcset de_de  "Copied %s" "%s wurde kopiert"
	::msgcat::mcset de_de  "Copy"  "Kopieren"
	::msgcat::mcset de_de  "Cut"  "Ausschneiden"
	::msgcat::mcset de_de  "Cut %s" "%s ausgeschnitten"
	::msgcat::mcset de_de  "Debug..." "Debuggen..."
	::msgcat::mcset de_de  "Default script not exists" "Startskript existiert nicht"
	::msgcat::mcset de_de  "Default script not specify!"  "Startskript nicht ausgewählt!"
	::msgcat::mcset de_de  "Delete"  "Löschen"
	::msgcat::mcset de_de  "Edit"  "Bearbeiten"
	::msgcat::mcset de_de  "Error"  "Fehler"
	::msgcat::mcset de_de  "File Properties..."  "Datei Eigenschaften..."
	::msgcat::mcset de_de  "File copy fail!"  "Datei kopieren fehlgeschlagen!"
	::msgcat::mcset de_de  "File name invalid." "Dateiname ist ungültig."
	::msgcat::mcset de_de  "Folder"  "Ordner"
	::msgcat::mcset de_de  "Folder already exists!"  "Ordner existier bereits!"
	::msgcat::mcset de_de  "Import to : (%s)" "Importieren nach : (%s)"
	::msgcat::mcset de_de  "Location : %s" "Ort : %s"
	::msgcat::mcset de_de  "New Folder"  "Neuer Ordner"
	::msgcat::mcset de_de  "New Item"  "Neues Objekt"
	::msgcat::mcset de_de  "No copy target"  "Kein Ziel für Kopieren"
	::msgcat::mcset de_de  "Ok" "Ok"
	::msgcat::mcset de_de  "Open" "Öffnen"
	::msgcat::mcset de_de  "Open As..."  "Öffnen als..."
	::msgcat::mcset de_de  "Open Project"  "Projekt öffnen"
	::msgcat::mcset de_de  "Others..."  "Andere..."
	::msgcat::mcset de_de  "Paste"  "Einfügen"
	::msgcat::mcset de_de  "Please specify Tcl or Tk interpreter first!" "Bitte zuerst den Tcl oder Tk Interpreter auswählen!"
	::msgcat::mcset de_de  "Project - %s" "Projekt - %s"
	::msgcat::mcset de_de  "Project Properties..."  "Projekt Eigenschaften..."
	::msgcat::mcset de_de  "Rename"  "Umbenennen"
	::msgcat::mcset de_de  "Rename fail!"  "Umbenennen fehlgeschlagen!"
	::msgcat::mcset de_de  "Replace" "Ersetzen"
	::msgcat::mcset de_de  "Run..."  "Ausführen..."
	::msgcat::mcset de_de  "Save Project.."  "Projekt speichern.."
	::msgcat::mcset de_de  "Set As Default Script"  "Als Startskript wählen"
	::msgcat::mcset de_de  "Syntax Check..." "Syntax Überprüfung..."
	::msgcat::mcset de_de  "The folder already contains a file named %s" "Der Ordner enthält bereits eine Datei mit dem Namen %s"
	::msgcat::mcset de_de  "The operation need close current project. Close project ?"  "Diese Operation wird das aktuelle Projekt schließen. Projekt schließen ?"
	::msgcat::mcset de_de  "refresh"  "Aktualisieren"
}

namespace eval ::fmeStatusBar {
	::msgcat::mcset de_de  "Lines"  "Zeilen"
	::msgcat::mcset de_de  "Pos"  "Pos"
}

namespace eval ::fmeTabEditor {
	::msgcat::mcset de_de  "'%s' has not save. save it ?" "'%s' wurd noch nicht gespeichert. Speichern ?"
	::msgcat::mcset de_de  "Cancal"  "Abbrechen"
	::msgcat::mcset de_de  "Copy %s - %s" "Kopieren %s - %s"
	::msgcat::mcset de_de  "Cut %s - %s" "Ausschneiden %s - %s"
	::msgcat::mcset de_de  "No Copy Region"  "Keine Region für Kopie ausgewählt"
	::msgcat::mcset de_de  "No Cut Region"  "Keine Region für Ausschneiden ausgewählt"
	::msgcat::mcset de_de  "Paste"  "Einfügen"
	::msgcat::mcset de_de  "Print"  "Drucken"
	::msgcat::mcset de_de  "Print Command:"  "Druckbefehl:"
}

namespace eval ::fmeTabMgr {
	::msgcat::mcset de_de  "Debug" "Debugger"
	::msgcat::mcset de_de  "File"  "Datei"
	::msgcat::mcset de_de  "Help" "Hilfe"
	::msgcat::mcset de_de  "Proc"  "Proc"
}

namespace eval ::fmeTask {
	::msgcat::mcset de_de  "Add Task"  "Aufgabe hinzufügen"
	::msgcat::mcset de_de  "All" "Alle"
	::msgcat::mcset de_de  "Are you sure you want to delete %%d tasks?" "Wollen Sie %%d Aufgaben entfernen?"
	::msgcat::mcset de_de  "Change State" "Zustand ändern"
	::msgcat::mcset de_de  "Delete"  "Entfernen"
	::msgcat::mcset de_de  "Delete Completed Tasks"  "Erledigte Aufgaben entfernen"
	::msgcat::mcset de_de  "Delete Task"  "Aufgabe entfernen"
	::msgcat::mcset de_de  "Description"  "Beschreibung"
	::msgcat::mcset de_de  "Do you want to delete completed task ?"  "Wollen Sie die erledigte Aufgabe entfernen ?"
	::msgcat::mcset de_de  "Do you want to delete task ?"  "Wollen Sie die Aufgabe löschen ?"
	::msgcat::mcset de_de  "Edit"  "Bearbeiten"
	::msgcat::mcset de_de  "Find" "Finden"
	::msgcat::mcset de_de  "Finished" "Abgeschlossen"
	::msgcat::mcset de_de  "Hide Completed Tasks" "Erledigte Aufgaben verbergen"
	::msgcat::mcset de_de  "In Progress" "In Bearbeitung"
	::msgcat::mcset de_de  "Not Started" "Noch nicht begonnen"
	::msgcat::mcset de_de  "Refresh"  "Aktualisieren"
	::msgcat::mcset de_de  "Reset" "Zurücksetzen"
	::msgcat::mcset de_de  "Search:" "Suchen:"
	::msgcat::mcset de_de  "State"  "Zustand"
	::msgcat::mcset de_de  "Task Delete"  "Aufgabe entfernen"
	::msgcat::mcset de_de  "Task already hidden!" "Aufgabe bereits verborgen!"
	::msgcat::mcset de_de  "Time"  "Zeit"
}

namespace eval ::fmeTaskMgr {
	::msgcat::mcset de_de  "Debug" "Debuggen"
	::msgcat::mcset de_de  "Nagelfar" "Nagelfar"
	::msgcat::mcset de_de  "Tasks"  "Aufgaben"
	::msgcat::mcset de_de  "TkCon"  "TkCon"
}

namespace eval ::fmeToolbar {
	::msgcat::mcset de_de  "Add Block Comment"  "Block als Kommentar markieren"
	::msgcat::mcset de_de  "Backward"  "Rückwärts"
	::msgcat::mcset de_de  "Case Sensitive"  "Groß/Kleinschreibung beachten"
	::msgcat::mcset de_de  "Copy"  "Kopieren"
	::msgcat::mcset de_de  "Cut"  "Ausschneiden"
	::msgcat::mcset de_de  "Debug Default Script..." "Startskript debuggen..."
	# New
	::msgcat::mcset de_de  "Debug current file" "Aktuelle Datei debuggen"
	# New
	::msgcat::mcset de_de  "Debug project" "Projekt debuggen"
	::msgcat::mcset de_de  "Debug..." "Debuggen..."
	::msgcat::mcset de_de  "File..."  "Datei..."
	::msgcat::mcset de_de  "Find"  "Suchen"
	::msgcat::mcset de_de  "Find Options"  "Such Optionen"
	::msgcat::mcset de_de  "Folder..."  "Ordner..."
	::msgcat::mcset de_de  "Ident Selection"  "Auswahl einrücken"
	::msgcat::mcset de_de  "MP3 Player" "MP3 Player"
	::msgcat::mcset de_de  "New"  "Neu"
	::msgcat::mcset de_de  "Open"  "Öffnen"
	::msgcat::mcset de_de  "Open File"  "Datei öffnen"
	::msgcat::mcset de_de  "Paste"  "Drucken"
	::msgcat::mcset de_de  "Print current editor..." "Print current editor..."
	::msgcat::mcset de_de  "Project..."  "Projekt..."
	::msgcat::mcset de_de  "Redo"  "Wiederholen"
	::msgcat::mcset de_de  "Regular Expression"  "Regulärer Ausdruck"
	::msgcat::mcset de_de  "Remove Block Comment"  "Kommentar von Block entfernen"
	::msgcat::mcset de_de  "Run Project..."  "Projekt ausführen..."
	::msgcat::mcset de_de  "Run..."  "Ausführen..."
	::msgcat::mcset de_de  "Save"  "Speichern"
	::msgcat::mcset de_de  "Save All"  "Alle speichern"
	::msgcat::mcset de_de  "Search files" "Dateien suchen"
	::msgcat::mcset de_de  "Search in files" "In Dateien suchen..."
	::msgcat::mcset de_de  "Start Debugger" "Debugger starten"
	::msgcat::mcset de_de  "Stop" "Stop"
	::msgcat::mcset de_de  "Stop '%s'" "Stoppe '%s'"
	::msgcat::mcset de_de  "Syntax check..." "Syntax Überprüfung..."
	::msgcat::mcset de_de  "UnIdent Selection"  "Auswahl ausrücken"
	::msgcat::mcset de_de  "Undo"  "Rückgängig"
}

namespace eval ::frmAbout {
	::msgcat::mcset de_de  "About CrowTDE"  "Über CrowTDE"
	# New
	::msgcat::mcset de_de  "Copyright (C) 2006-2007 Tai, Yuan-Liang & Zheng, Shao-Huan" "Copyright (C) 2006-2007 Tai, Yuan-Liang & Zheng, Shao-Huan"
	::msgcat::mcset de_de  "Credits" "Credits"
	::msgcat::mcset de_de  "CrowTDE License" "CrowTDE Lizenz"
	::msgcat::mcset de_de  "CrowTDE is an open source Tcl/Tk development %s environment written in Tcl/Tk. Its purposes is to provide a %s convenient environment for Tcl/Tk programmers." "CrowTDE ist eine Open Source Tcl/Tk Entwicklungsumgebung %s geschrieben in Tcl/Tk. %s Es soll eine komfortable Umgebung für Tcl/Tk Entwickler sein."
	::msgcat::mcset de_de  "Exit" "Schließen"
	::msgcat::mcset de_de  "German - Michael Schlenker <mic42@user.sourceforge.net> %s" "Deutsch - Michael Schlenker <mic42@user.sourceforge.net> %s"
	# New
	::msgcat::mcset de_de  "Italian - Diego <siarodx@gmail.com> %s" "Italienisch - Diego <siarodx@gmail.com> %s"
	::msgcat::mcset de_de  "License" "Lizenz"
	::msgcat::mcset de_de  "License:" "Lizenz:"
	::msgcat::mcset de_de  "Traditional Chinese - Zang, Ke-Yuan <jarry@crow.ee.stut.edu.tw> %s" "Traditionales Chinesisch - Zang, Ke-Yuan <jarry@crow.ee.stut.edu.tw> %s"
	::msgcat::mcset de_de  "Translators" "Übersetzer"
	::msgcat::mcset de_de  "Visit : http://crow.ee.stut.edu.tw/dai/crowtde/" "Besuchen Sie : http://crow.ee.stut.edu.tw/dai/crowtde/"
}

namespace eval ::frmCheckSave {
	::msgcat::mcset de_de  "Cancel"  "Abbrechen"
	::msgcat::mcset de_de  "No"  "Nein"
	::msgcat::mcset de_de  "Save"  "Speichern"
	::msgcat::mcset de_de  "Save files ?" "Dateien speichern ?"
	::msgcat::mcset de_de  "Yes"  "Ja"
}

namespace eval ::frmFirst {
	::msgcat::mcset de_de  "Basic Settings"  "Grundeinstellungen"
	::msgcat::mcset de_de  "Browse..."  "Durchsuchen..."
	::msgcat::mcset de_de  "Information"  "Informationen"
	::msgcat::mcset de_de  "Language:"  "Sprache:"
	::msgcat::mcset de_de  "Ok"  "Ok"
	::msgcat::mcset de_de  "Open File"  "Datei öffnen"
	::msgcat::mcset de_de  "Tcl Interpreter:"  "Tcl Interpreter:"
	::msgcat::mcset de_de  "Tk Interpreter:"  "Tk Interpreter:"
	::msgcat::mcset de_de  "You are first time running CrowTDE.%s Please configure your basic run-time environment." "Sie benutzen CrowTDE.%s das erste Mal. Bitte konfigurieren Sie die Laufzeiteinstellungen."
	::msgcat::mcset de_de  "You can configure more details from 'Main Menu->Options->Settings' ."  "Sie können mehr Details unter 'Hauptmenü->Optionen->Einstellungen' konfigurieren."
}

namespace eval ::frmNewProject {
	::msgcat::mcset de_de  "'%s' already exists." "'%s' existiert bereits."
	::msgcat::mcset de_de  "Browse..."  "Durchsuchen..."
	::msgcat::mcset de_de  "Cancel"  "Abbrechen"
	::msgcat::mcset de_de  "Create"  "Anlegen"
	::msgcat::mcset de_de  "Default Script:"  "Startskript:"
	::msgcat::mcset de_de  "Error"  "Fehler"
	::msgcat::mcset de_de  "Interpreter"  "Interpreter"
	::msgcat::mcset de_de  "Interpreter:"  "Interpreter:"
	::msgcat::mcset de_de  "New Project"  "Neues Projekt"
	::msgcat::mcset de_de  "Please choose template first!"  "Bitte zuerst die Vorlage auswählen!"
	::msgcat::mcset de_de  "Project Name:"  "Projekt Name:"
	::msgcat::mcset de_de  "Template:"  "Vorlage:"
	::msgcat::mcset de_de  "Workspace"  "Arbeitsbereich"
	::msgcat::mcset de_de  "Workspace:"  "Arbeitsbereich:"
}

namespace eval ::frmProjectProperty {
	::msgcat::mcset de_de  "Browse..."  "Durchsuchen..."
	::msgcat::mcset de_de  "Cancel"  "Abbrechen"
	::msgcat::mcset de_de  "Default Script:"  "Startskript:"
	::msgcat::mcset de_de  "Interpreter"  "Interpreter"
	::msgcat::mcset de_de  "Interpreter:"  "Interpreter:"
	::msgcat::mcset de_de  "Ok"  "Ok"
	::msgcat::mcset de_de  "Project Name:"  "Projekt Name:"
	::msgcat::mcset de_de  "Project Properties"  "Projekt Eigenschaften"
	::msgcat::mcset de_de  "Workspace:"  "Arbeitsbereich:"
}

namespace eval ::frmSearchFiles {
	::msgcat::mcset de_de  "Browse..."  "Durchsuchen..."
	::msgcat::mcset de_de  "Choose Directory"  "Ordner auswählen"
	::msgcat::mcset de_de  "Directory:"  "Ordner:"
	::msgcat::mcset de_de  "Error"  "Fehler"
	::msgcat::mcset de_de  "File name:"  "Dateiname:"
	::msgcat::mcset de_de  "Finish %s items found." "Beendet, %s Objekte gefunden."
	::msgcat::mcset de_de  "Keyword can't empty!"  "Suchbegriff darf nicht leer sein!"
	::msgcat::mcset de_de  "Search directory not valid!"  "Ordner für Suche ungültig!"
	::msgcat::mcset de_de  "Search files" "Dateien suchen"
	::msgcat::mcset de_de  "Search hidden files & folders"  "Versteckte Dateien und Ordner durchsuchen"
	::msgcat::mcset de_de  "Start"  "Start"
	::msgcat::mcset de_de  "Stop"  "Stop"
}

namespace eval ::frmSearchInFiles {
	::msgcat::mcset de_de  "Browse..."  "Durchsuchen..."
	::msgcat::mcset de_de  "Case Sensitive"  "Groß/Kleinschreibung beachten"
	::msgcat::mcset de_de  "Choose Directory"  "Ordner auswählen"
	::msgcat::mcset de_de  "Directory"  "Ordner"
	::msgcat::mcset de_de  "Error"  "Fehler"
	::msgcat::mcset de_de  "Filter:"  "Filter:"
	::msgcat::mcset de_de  "Keyword can't empty!"  "Suchbegriff darf nicht leer sein!"
	::msgcat::mcset de_de  "Keyword:"  "Suchbegriff:"
	::msgcat::mcset de_de  "Regular Expression"  "Regulärer Ausdruck"
	::msgcat::mcset de_de  "Search directory not valid!"  "Ordner für Suche ungültig!"
	::msgcat::mcset de_de  "Search hidden files & folders"  "Versteckte Dateien und Ordner durchsuchen"
	::msgcat::mcset de_de  "Search in files" "In Dateien suchen..."
	::msgcat::mcset de_de  "Start"  "Start"
	::msgcat::mcset de_de  "Stop"  "Stop"
}

namespace eval ::frmSetting {
	::msgcat::mcset de_de  "CrowTDE configuration" "CrowTDE Einstellungen"
	::msgcat::mcset de_de  "Editor Settings" "Editor Einstellungen"
	::msgcat::mcset de_de  "Exit"  "Beenden"
	::msgcat::mcset de_de  "File Settings" "Datei Einstellungen"
	::msgcat::mcset de_de  "Fonts"  "Schriftarten"
	::msgcat::mcset de_de  "General"  "Allgemein"
}

namespace eval ::frmStartPage {
	::msgcat::mcset de_de  "Browse..."  "Durchsuchen..."
	::msgcat::mcset de_de  "Cancel"  "Abbrechen"
	::msgcat::mcset de_de  "Create New Project..."  "Neues Projekt anlegen..."
	::msgcat::mcset de_de  "CrowTDE Start Page"  "CrowTDE Startseite"
	::msgcat::mcset de_de  "Ok"  "Ok"
	::msgcat::mcset de_de  "Open Last Project (%s)" "Letztes Projekt öffnen (%s)"
	::msgcat::mcset de_de  "Open Project"  "Projekt öffnen"
	::msgcat::mcset de_de  "Please Choose Function"  "Bitte auswählen"
	::msgcat::mcset de_de  "Project:"  "Projekt:"
}

namespace eval ::svnWrapper {
	# New
	::msgcat::mcset de_de  "...ok!" "...ok!"
	# New
	::msgcat::mcset de_de  "Add" "Datei oder Ordner hinzufügen"
	# New
	::msgcat::mcset de_de  "Are you want to remove '%s' propeties?" "Wollen sie die SVN Eigenschaft '%s' entfernen?"
	# New
	::msgcat::mcset de_de  "Cancel" "Abbrechen"
	# New
	::msgcat::mcset de_de  "Check for modifications" "Auf Änderungen prüfen"
	# New
	::msgcat::mcset de_de  "Checkout" "Checkout"
	# New
	::msgcat::mcset de_de  "Checkout directory:" "Checkout Ordner:"
	# New
	::msgcat::mcset de_de  "Checkout from SVN" "Aus SVN auschecken"
	# New
	::msgcat::mcset de_de  "Choose Directory" "Ordner wählen"
	# New
	::msgcat::mcset de_de  "Clean up" "Aufräumen"
	# New
	::msgcat::mcset de_de  "Commit" "SVN Commit"
	# New
	::msgcat::mcset de_de  "Commit to : %s" "Commit in : %s"
	# New
	::msgcat::mcset de_de  "Delete" "Löschen"
	# New
	::msgcat::mcset de_de  "Directory can't empty." "Ordner darf nicht leer sein"
	# New
	::msgcat::mcset de_de  "Directory:" "Ordner:"
	# New
	::msgcat::mcset de_de  "Edit" "Bearbeiten"
	# New
	::msgcat::mcset de_de  "Error!" "Fehler!"
	# New
	::msgcat::mcset de_de  "Export" "Exportieren"
	# New
	::msgcat::mcset de_de  "Export: %s" "Exportiern: %s"
	# New
	::msgcat::mcset de_de  "File list is empty!" "Dateiliste ist leer!"
	# New
	::msgcat::mcset de_de  "HEAD revision" "HEAD Revision"
	# New
	::msgcat::mcset de_de  "Import" "Importieren"
	# New
	::msgcat::mcset de_de  "Import Message:" "Import Meldung:"
	# New
	::msgcat::mcset de_de  "Include ignored files" "Ignorierte Dateien berücksichtigen"
	# New
	::msgcat::mcset de_de  "Include unversion file(s)" "Nicht versionierte Dateien berücksichtigen"
	# New
	::msgcat::mcset de_de  "Login" "Login"
	# New
	::msgcat::mcset de_de  "Message : " "Meldung : "
	# New
	::msgcat::mcset de_de  "Move" "Verschieben"
	# New
	::msgcat::mcset de_de  "Move to:" "Verschieben nach:"
	# New
	::msgcat::mcset de_de  "No files were changed or added since the last commit." "Keine neuen oder geänderten Dateien seit dem letzten Commit."
	# New
	::msgcat::mcset de_de  "Not thing to do." "Nichts zu tun."
	# New
	::msgcat::mcset de_de  "Ok" "Ok"
	# New
	::msgcat::mcset de_de  "Passwd:" "Passwort:"
	# New
	::msgcat::mcset de_de  "Please select a property first!" "Bitte zuerste eine Eigenschaft auswählen!"
	# New
	::msgcat::mcset de_de  "Please wait" "Bitte warten"
	# New
	::msgcat::mcset de_de  "Properties" "Eigenschaften"
	# New
	::msgcat::mcset de_de  "Property" "Eigenschaft"
	# New
	::msgcat::mcset de_de  "Property :" "Eigenschaft :"
	# New
	::msgcat::mcset de_de  "Remove" "Entfernen"
	# New
	::msgcat::mcset de_de  "Remove properties" "Eigenschaften entfernen"
	# New
	::msgcat::mcset de_de  "Rename" "Datei Umbenennen"
	# New
	::msgcat::mcset de_de  "Repository:" "Repositorium:"
	# New
	::msgcat::mcset de_de  "Resolved" "Konflikt bereinigt"
	# New
	::msgcat::mcset de_de  "Revert" "Zu vorheriger Revision zurück"
	# New
	::msgcat::mcset de_de  "Revision" "Revision"
	# New
	::msgcat::mcset de_de  "SVN Update" "SVN Update"
	# New
	::msgcat::mcset de_de  "Status" "SVN Status"
	# New
	::msgcat::mcset de_de  "Subversion" "Subversion"
	# New
	::msgcat::mcset de_de  "Svn" "Svn"
	# New
	::msgcat::mcset de_de  "Target : %s" "Ziel : %s"
	# New
	::msgcat::mcset de_de  "URL can't empty." "URL darf nicht leer sein."
	# New
	::msgcat::mcset de_de  "URL of repository:" "URL des Repositoriums:"
	# New
	::msgcat::mcset de_de  "Update" "SVN Update"
	# New
	::msgcat::mcset de_de  "Username:" "Benutzername:"
	# New
	::msgcat::mcset de_de  "Value" "Wert"
	# New
	::msgcat::mcset de_de  "Value :" "Wert :"
	# New
	::msgcat::mcset de_de  "error" "Fehler"
	# New
	::msgcat::mcset de_de  "update" "SVN Update"
}

namespace eval ::crowTemplate {
	#New
	::msgcat::mcset zh_tw "Empty file" "Leere Datei"
	#New
	::msgcat::mcset zh_tw "Tcl Package" "Tcl Package"
	
	#New
	::msgcat::mcset zh_tw "Create an empty project." "Neues leeres Projekt erzeugen."	
	# New
	::msgcat::mcset zh_tw  "Checkout project from SVN Repository." "Projekt aus SVN Repositorium auschecken."
	# New
	::msgcat::mcset zh_tw  "SVN Project" "SVN Projekt"
}
