namespace eval ::crowDebugger {
	# New
	::msgcat::mcset en_us  "...abort" "...abort"
	# New
	::msgcat::mcset en_us  "...ok" "...ok"
	# New
	::msgcat::mcset en_us  "Debug script is not specified or not exists.!" "Debug script is not specified or not exists.!"
	# New
	::msgcat::mcset en_us  "Debugger already running!" "Debugger already running!"
	# New
	::msgcat::mcset en_us  "Debugger has not started!" "Debugger has not started!"
	# New
	::msgcat::mcset en_us  "Error" "Error"
	# New
	::msgcat::mcset en_us  "Interpreter is not specified or not exists!" "Interpreter is not specified or not exists!"
	# New
	::msgcat::mcset en_us  "Loading '%s' ..." "Loading '%s' ..."
	# New
	::msgcat::mcset en_us  "Start Debugger...ok" "Start Debugger...ok"
	# New
	::msgcat::mcset en_us  "Stop Debugger....ok" "Stop Debugger....ok"
	# New
	::msgcat::mcset en_us  "error" "error"
}

namespace eval ::crowEditor {
	::msgcat::mcset en_us  "'%s' has been delete from the file system. Save it?" "'%s' has been delete from the file system. Save it?"
	::msgcat::mcset en_us  "'%s' has been deleted from the file system. Save ?" "'%s' has been deleted from the file system. Save ?"
	::msgcat::mcset en_us  "'%s' has been modified. Reload file ?" "'%s' has been modified. Reload file ?"
	::msgcat::mcset en_us  "'%s' has been modified. Save changes ?" "'%s' has been modified. Save changes ?"
	::msgcat::mcset en_us  "Add Block Comment"  "Add Block Comment"
	::msgcat::mcset en_us  "Backward"  "Backward"
	::msgcat::mcset en_us  "Case Sensitive"  "Case Sensitive"
	::msgcat::mcset en_us  "Colors"  "Colors"
	::msgcat::mcset en_us  "Comment:" "Comment:"
	::msgcat::mcset en_us  "Copy"  "Copy"
	::msgcat::mcset en_us  "Cut"  "Cut"
	::msgcat::mcset en_us  "Cut Line"  "Cut Line"
	::msgcat::mcset en_us  "Cut word"  "Cut word"
	::msgcat::mcset en_us  "Default disabled"  "Default disabled"
	::msgcat::mcset en_us  "Default enabled"  "Default enabled"
	::msgcat::mcset en_us  "Delete"  "Delete"
	# New
	::msgcat::mcset en_us  "Editor Settings" "Editor Settings"
	::msgcat::mcset en_us  "Exit"  "Exit"
	::msgcat::mcset en_us  "Find"  "Find"
	::msgcat::mcset en_us  "Find And Replace"  "Find And Replace"
	::msgcat::mcset en_us  "Find Next"  "Find Next"
	::msgcat::mcset en_us  "Find/Replace..."  "Find/Replace..."
	::msgcat::mcset en_us  "Indent Selection"  "Indent Selection"
	::msgcat::mcset en_us  "Information"  "Information"
	::msgcat::mcset en_us  "Information!" "Information!"
	::msgcat::mcset en_us  "Insert Macro"  "Insert Macro"
	::msgcat::mcset en_us  "Items"  "Items"
	::msgcat::mcset en_us  "Jump To"  "Jump To"
	::msgcat::mcset en_us  "Jump To..."  "Jump To..."
	::msgcat::mcset en_us  "Numerical:" "Numerical:"
	::msgcat::mcset en_us  "Paste"  "Paste"
	::msgcat::mcset en_us  "Redo"  "Redo"
	::msgcat::mcset en_us  "Regular expression"  "Regular expression"
	::msgcat::mcset en_us  "Remove Block Comment"  "Remove Block Comment"
	::msgcat::mcset en_us  "Repalce All"  "Repalce All"
	::msgcat::mcset en_us  "Replace"  "Replace"
	::msgcat::mcset en_us  "Reset"  "Reset"
	::msgcat::mcset en_us  "Save"  "Save"
	::msgcat::mcset en_us  "Save File"  "Save File"
	::msgcat::mcset en_us  "Save Macro"  "Save Macro"
	::msgcat::mcset en_us  "Save file!"  "Save file!"
	::msgcat::mcset en_us  "Save success"  "Save success"
	::msgcat::mcset en_us  "Select All"  "Select All"
	::msgcat::mcset en_us  "Select Line"  "Select Line"
	::msgcat::mcset en_us  "Select word"  "Select word"
	# New
	::msgcat::mcset en_us  "Set Breakpoint" "Set Breakpoint"
	::msgcat::mcset en_us  "String Not Found"  "String Not Found"
	::msgcat::mcset en_us  "String:" "String:"
	::msgcat::mcset en_us  "Syntax Highlight"  "Syntax Highlight"
	# New
	::msgcat::mcset en_us  "Tab width" "Tab width"
	# New
	::msgcat::mcset en_us  "Tcl Argument:" "Tcl Argument:"
	# New
	::msgcat::mcset en_us  "Tcl Command:" "Tcl Command:"
	# New
	::msgcat::mcset en_us  "Tk Argument:" "Tk Argument:"
	# New
	::msgcat::mcset en_us  "Tk Command:" "Tk Command:"
	::msgcat::mcset en_us  "Undo"  "Undo"
	::msgcat::mcset en_us  "Unindent Selection"  "Unindent Selection"
	# New
	::msgcat::mcset en_us  "Unset Breakpoint" "Unset Breakpoint"
	::msgcat::mcset en_us  "Variable:" "Variable:"
	::msgcat::mcset en_us  "Warring!"  "Warring!"
}

namespace eval ::crowExec {
	# New
	::msgcat::mcset en_us  "%s...Exit" "%s...Exit"
	# New
	::msgcat::mcset en_us  "Error" "Error"
	# New
	::msgcat::mcset en_us  "Interpreter '%s' not exists" "Interpreter '%s' not exists"
	# New
	::msgcat::mcset en_us  "Permission denied" "Permission denied"
	# New
	::msgcat::mcset en_us  "Run %s..." "Run %s..."
	# New
	::msgcat::mcset en_us  "You may not permission to execuate this file! Execuate force?" "You may not permission to execuate this file! Execuate force?"
}

namespace eval ::crowFileProperties {
	::msgcat::mcset en_us  "Accept" "Accept"
	::msgcat::mcset en_us  "Accessed:" "Accessed:"
	::msgcat::mcset en_us  "Cancel" "Cancel"
	::msgcat::mcset en_us  "Changed:" "Changed:"
	::msgcat::mcset en_us  "File Properties" "File Properties"
	::msgcat::mcset en_us  "General" "General"
	::msgcat::mcset en_us  "Group" "Group"
	::msgcat::mcset en_us  "Location:" "Location:"
	::msgcat::mcset en_us  "Modified:" "Modified:"
	::msgcat::mcset en_us  "Name:" "Name:"
	::msgcat::mcset en_us  "Other" "Other"
	::msgcat::mcset en_us  "Owner" "Owner"
	::msgcat::mcset en_us  "Permissions" "Permissions"
	::msgcat::mcset en_us  "Read" "Read"
	::msgcat::mcset en_us  "SID" "SID"
	::msgcat::mcset en_us  "Set GID" "Set GID"
	::msgcat::mcset en_us  "Set UID" "Set UID"
	::msgcat::mcset en_us  "Size:" "Size:"
	::msgcat::mcset en_us  "Type:" "Type:"
	::msgcat::mcset en_us  "Write" "Write"
	::msgcat::mcset en_us  "execute" "execute"
	::msgcat::mcset en_us  "recursive apply" "recursive apply"
}

namespace eval ::crowFileRelation {
	::msgcat::mcset en_us  "Add"  "Add"
	::msgcat::mcset en_us  "All"  "All"
	::msgcat::mcset en_us  "Application"  "Application"
	# New
	::msgcat::mcset en_us  "Application:" "Application:"
	::msgcat::mcset en_us  "Browse..."  "Browse..."
	# New
	::msgcat::mcset en_us  "File Extension:" "File Extension:"
	::msgcat::mcset en_us  "File Relation Setting"  "File Relation Setting"
	::msgcat::mcset en_us  "File types"  "File types"
	::msgcat::mcset en_us  "Remove"  "Remove"
	::msgcat::mcset en_us  "Setting default"  "Setting default"
}

namespace eval ::crowFont {
	::msgcat::mcset en_us  "Apply"  "Apply"
	::msgcat::mcset en_us  "Editor font"  "Editor font"
	::msgcat::mcset en_us  "Fonts setting"  "Fonts setting"
	::msgcat::mcset en_us  "Large font"  "Large font"
	::msgcat::mcset en_us  "Menu font"  "Menu font"
	::msgcat::mcset en_us  "Small font"  "Small font"
	::msgcat::mcset en_us  "normal font"  "normal font"
}

namespace eval ::crowGetDir {
	::msgcat::mcset en_us  "'%s' has been deleted from the file system!" "'%s' has been deleted from the file system!"
	::msgcat::mcset en_us  "Cancel" "Cancel"
	::msgcat::mcset en_us  "Choose Direcotry" "Choose Direcotry"
	::msgcat::mcset en_us  "Choose Folder First!" "Choose Folder First!"
	::msgcat::mcset en_us  "Error" "Error"
	::msgcat::mcset en_us  "Folder Already Exists!" "Folder Already Exists!"
	::msgcat::mcset en_us  "New Folder" "New Folder"
	::msgcat::mcset en_us  "Ok" "Ok"
}

namespace eval ::crowIO {
	::msgcat::mcset en_us  "Cancel"  "Cancel"
	::msgcat::mcset en_us  "Ok" "Ok"
	::msgcat::mcset en_us  "Wrong argument!"  "Wrong argument!"
	::msgcat::mcset en_us  "gets" "gets"
	::msgcat::mcset en_us  "read" "read"
}

namespace eval ::crowMacro {
	::msgcat::mcset en_us  ""  ""
	::msgcat::mcset en_us  "--Delete This Folder--" "--Delete This Folder--"
	::msgcat::mcset en_us  "Are you sure you want to delete macro?"  "Are you sure you want to delete macro?"
	::msgcat::mcset en_us  "Browse" "Browse"
	::msgcat::mcset en_us  "Cancel"  "Cancel"
	::msgcat::mcset en_us  "Codes:" "Codes:"
	::msgcat::mcset en_us  "Delete"  "Delete"
	::msgcat::mcset en_us  "Macro Name:" "Macro Name:"
	::msgcat::mcset en_us  "Ok"  "Ok"
	::msgcat::mcset en_us  "Operations"  "Operations"
	::msgcat::mcset en_us  "Save Macro"  "Save Macro"
	::msgcat::mcset en_us  "Save Path:" "Save Path:"
	::msgcat::mcset en_us  "System Define"  "System Define"
	::msgcat::mcset en_us  "User Define"  "User Define"
}

namespace eval ::crowRC {
	::msgcat::mcset en_us  "Create fail!"  "Create fail!"
	::msgcat::mcset en_us  "Error"  "Error"
}

namespace eval ::crowSdx {
	::msgcat::mcset en_us  "%s Elapsed time ... %02s:%02s" "%s Elapsed time ... %02s:%02s"
	::msgcat::mcset en_us  "Browse" "Browse"
	::msgcat::mcset en_us  "Building starkit ..." "Building starkit ..."
	::msgcat::mcset en_us  "Cancel" "Cancel"
	::msgcat::mcset en_us  "Do not compress files added to starkit" "Do not compress files added to starkit"
	::msgcat::mcset en_us  "Finish." "Finish."
	::msgcat::mcset en_us  "Move '%s' -> '%s'" "Move '%s' -> '%s'"
	::msgcat::mcset en_us  "Ok" "Ok"
	::msgcat::mcset en_us  "Options" "Options"
	::msgcat::mcset en_us  "SDX" "SDX"
	::msgcat::mcset en_us  "Save As.." "Save As.."
	::msgcat::mcset en_us  "Save to:" "Save to:"
	::msgcat::mcset en_us  "Script:" "Script:"
	::msgcat::mcset en_us  "Size = %s (KB)" "Size = %s (KB)"
	::msgcat::mcset en_us  "Starkit runtime not exists!" "Starkit runtime not exists!"
	::msgcat::mcset en_us  "VFS Directory:" "VFS Directory:"
	::msgcat::mcset en_us  "Writable" "Writable"
	::msgcat::mcset en_us  "error" "error"
	::msgcat::mcset en_us  "include runtime" "include runtime"
}

namespace eval ::crowSyntax {
	::msgcat::mcset en_us  "Cancel" "Cancel"
	::msgcat::mcset en_us  "Ok" "Ok"
}

namespace eval ::crowTde {
	::msgcat::mcset en_us  "CrowTDE Start success, thanks for use ^o^" "CrowTDE Start success, thanks for use ^o^"
	# New
	::msgcat::mcset en_us  "Loading plugin '%s' ..." "Loading plugin '%s' ..."
}

namespace eval ::crowThread {
	::msgcat::mcset en_us  "%s Finish" "%s Finish"
	::msgcat::mcset en_us  "Error"  "Error"
	::msgcat::mcset en_us  "Interpreter '%s' not exists" "Interpreter '%s' not exists"
	# New
	::msgcat::mcset en_us  "Permission denied" "Permission denied"
	::msgcat::mcset en_us  "Run %s ..." "Run %s ..."
	# New
	::msgcat::mcset en_us  "You may not permission to execuate this file! Execuate force?" "You may not permission to execuate this file! Execuate force?"
}

namespace eval ::fmeDebugger {
	# New
	::msgcat::mcset en_us  "Add Watch" "Add Watch"
	# New
	::msgcat::mcset en_us  "Add Watch..." "Add Watch..."
	# New
	::msgcat::mcset en_us  "Breakpoints" "Breakpoints"
	# New
	::msgcat::mcset en_us  "Change Value..." "Change Value..."
	# New
	::msgcat::mcset en_us  "Change value" "Change value"
	# New
	::msgcat::mcset en_us  "Currently-Visible Variables" "Currently-Visible Variables"
	# New
	::msgcat::mcset en_us  "Debug" "Debug"
	# New
	::msgcat::mcset en_us  "Debug Default Script..." "Debug Default Script..."
	# New
	::msgcat::mcset en_us  "Debug level" "Debug level"
	# New
	::msgcat::mcset en_us  "Debug..." "Debug..."
	# New
	::msgcat::mcset en_us  "Deep" "Deep"
	# New
	::msgcat::mcset en_us  "Free go" "Free go"
	# New
	::msgcat::mcset en_us  "Info" "Info"
	# New
	::msgcat::mcset en_us  "Lines:" "Lines:"
	# New
	::msgcat::mcset en_us  "Normal" "Normal"
	# New
	::msgcat::mcset en_us  "Pause" "Pause"
	# New
	::msgcat::mcset en_us  "Position:" "Position:"
	# New
	::msgcat::mcset en_us  "Remove" "Remove"
	# New
	::msgcat::mcset en_us  "Remove Watch" "Remove Watch"
	# New
	::msgcat::mcset en_us  "Script:" "Script:"
	# New
	::msgcat::mcset en_us  "Shallow" "Shallow"
	# New
	::msgcat::mcset en_us  "Start Debugger" "Start Debugger"
	# New
	::msgcat::mcset en_us  "Step" "Step"
	# New
	::msgcat::mcset en_us  "Stop debugging" "Stop debugging"
	# New
	::msgcat::mcset en_us  "View" "View"
	# New
	::msgcat::mcset en_us  "Watch Variables" "Watch Variables"
	# New
	::msgcat::mcset en_us  "Watchpoint already exists!" "Watchpoint already exists!"
}

namespace eval ::fmeDocView {
	# New
	::msgcat::mcset en_us  "Collapse" "Collapse"
	::msgcat::mcset en_us  "Copy" "Copy"
	::msgcat::mcset en_us  "Copy %d %s" "Copy %d %s"
	# New
	::msgcat::mcset en_us  "Document Viewer(%s)" "Document Viewer(%s)"
	# New
	::msgcat::mcset en_us  "Home" "Home"
	# New
	::msgcat::mcset en_us  "Next" "Next"
	# New
	::msgcat::mcset en_us  "Previous" "Previous"
	# New
	::msgcat::mcset en_us  "Top" "Top"
	::msgcat::mcset en_us  "View in new window" "View in new window"
}

namespace eval ::fmeGenericSetting {
	::msgcat::mcset en_us  "Browse..."  "Browse..."
	::msgcat::mcset en_us  "Choose Tcl interpreter"  "Choose Tcl interpreter"
	::msgcat::mcset en_us  "Choose Tk interpreter"  "Choose Tk interpreter"
	::msgcat::mcset en_us  "Create new project"  "Create new project"
	# New
	::msgcat::mcset en_us  "Debug Level" "Debug Level"
	# New
	::msgcat::mcset en_us  "Deep" "Deep"
	::msgcat::mcset en_us  "Do nothing"  "Do nothing"
	::msgcat::mcset en_us  "General Settings"  "General Settings"
	::msgcat::mcset en_us  "Interpreter"  "Interpreter"
	# New
	::msgcat::mcset en_us  "Normal" "Normal"
	::msgcat::mcset en_us  "Open last edit project"  "Open last edit project"
	# New
	::msgcat::mcset en_us  "Shallow" "Shallow"
	::msgcat::mcset en_us  "Show startup page"  "Show startup page"
	::msgcat::mcset en_us  "Startup"  "Startup"
	::msgcat::mcset en_us  "Tcl Interpreter:" "Tcl Interpreter:"
	::msgcat::mcset en_us  "Tk Interpreter:" "Tk Interpreter:"
}

namespace eval ::fmeMenuBar {
	::msgcat::mcset en_us  "About..."  "About..."
	::msgcat::mcset en_us  "Add %s" "Add %s"
	::msgcat::mcset en_us  "Add Block Comment"  "Add Block Comment"
	::msgcat::mcset en_us  "Add Task"  "Add Task"
	# New
	::msgcat::mcset en_us  "Add Watch..." "Add Watch..."
	# New
	::msgcat::mcset en_us  "Adjust Tab Width" "Adjust Tab Width"
	::msgcat::mcset en_us  "Build ' %s ' ..." "Build ' %s ' ..."
	::msgcat::mcset en_us  "Build ..." "Build ..."
	::msgcat::mcset en_us  "Build Project..." "Build Project..."
	::msgcat::mcset en_us  "Close"  "Close"
	::msgcat::mcset en_us  "Close All"  "Close All"
	::msgcat::mcset en_us  "Close Project"  "Close Project"
	::msgcat::mcset en_us  "Collapse Toolbar"  "Collapse Toolbar"
	::msgcat::mcset en_us  "Copy"  "Copy"
	::msgcat::mcset en_us  "Cut"  "Cut"
	# New
	::msgcat::mcset en_us  "Debug" "Debug"
	# New
	::msgcat::mcset en_us  "Debug Default Script..." "Debug Default Script..."
	# New
	::msgcat::mcset en_us  "Debug level" "Debug level"
	# New
	::msgcat::mcset en_us  "Debug..." "Debug..."
	# New
	::msgcat::mcset en_us  "Deep" "Deep"
	::msgcat::mcset en_us  "Default Disabled"  "Default Disabled"
	::msgcat::mcset en_us  "Default Enabled"  "Default Enabled"
	# New
	::msgcat::mcset en_us  "Default script not exists!" "Default script not exists!"
	::msgcat::mcset en_us  "Delete"  "Delete"
	::msgcat::mcset en_us  "Delete ' %s '" "Delete ' %s '"
	::msgcat::mcset en_us  "Delete Completed Tasks"  "Delete Completed Tasks"
	::msgcat::mcset en_us  "Diabled All"  "Diabled All"
	::msgcat::mcset en_us  "Disabled Current Editor"  "Disabled Current Editor"
	::msgcat::mcset en_us  "Edit"  "Edit"
	::msgcat::mcset en_us  "Editor Details"  "Editor Details"
	::msgcat::mcset en_us  "Enabled All"  "Enabled All"
	::msgcat::mcset en_us  "Enabled Current Editor"  "Enabled Current Editor"
	::msgcat::mcset en_us  "Exit"  "Exit"
	::msgcat::mcset en_us  "Expand Toolbar"  "Expand Toolbar"
	::msgcat::mcset en_us  "File"  "File"
	::msgcat::mcset en_us  "File Relation"  "File Relation"
	::msgcat::mcset en_us  "Find/Replace..."  "Find/Replace..."
	::msgcat::mcset en_us  "Folder..."  "Folder..."
	# New
	::msgcat::mcset en_us  "Free Go" "Free Go"
	::msgcat::mcset en_us  "Help"  "Help"
	::msgcat::mcset en_us  "Import..."  "Import..."
	::msgcat::mcset en_us  "Indent Selection"  "Indent Selection"
	::msgcat::mcset en_us  "Insert Macro"  "Insert Macro"
	::msgcat::mcset en_us  "Jump To..."  "Jump To..."
	::msgcat::mcset en_us  "Language"  "Language"
	::msgcat::mcset en_us  "Locale"  "Locale"
	::msgcat::mcset en_us  "MP3 Directory - %s" "MP3 Directory - %s"
	::msgcat::mcset en_us  "MP3 Player Details"  "MP3 Player Details"
	::msgcat::mcset en_us  "New"  "New"
	::msgcat::mcset en_us  "Next Page"  "Next Page"
	# New
	::msgcat::mcset en_us  "Normal" "Normal"
	::msgcat::mcset en_us  "Open"  "Open"
	::msgcat::mcset en_us  "Open File"  "Open File"
	::msgcat::mcset en_us  "Open File..."  "Open File..."
	::msgcat::mcset en_us  "Open Project..."  "Open Project..."
	::msgcat::mcset en_us  "Options"  "Options"
	::msgcat::mcset en_us  "Paste"  "Paste"
	# New
	::msgcat::mcset en_us  "Pause" "Pause"
	::msgcat::mcset en_us  "Previous Page"  "Previous Page"
	::msgcat::mcset en_us  "Print..."  "Print..."
	::msgcat::mcset en_us  "Printer Setup*"  "Printer Setup*"
	::msgcat::mcset en_us  "Proc Details"  "Proc Details"
	::msgcat::mcset en_us  "Project"  "Project"
	::msgcat::mcset en_us  "Project..."  "Project..."
	::msgcat::mcset en_us  "Properties..."  "Properties..."
	::msgcat::mcset en_us  "Raise"  "Raise"
	::msgcat::mcset en_us  "Recent Files"  "Recent Files"
	::msgcat::mcset en_us  "Recent Projects"  "Recent Projects"
	::msgcat::mcset en_us  "Redo"  "Redo"
	::msgcat::mcset en_us  "Refresh"  "Refresh"
	::msgcat::mcset en_us  "Refresh Interval (%s ms)" "Refresh Interval (%s ms)"
	::msgcat::mcset en_us  "Remove Block Comment"  "Remove Block Comment"
	::msgcat::mcset en_us  "Run Default Script..." "Run Default Script..."
	::msgcat::mcset en_us  "Run..."  "Run..."
	::msgcat::mcset en_us  "Save"  "Save"
	::msgcat::mcset en_us  "Save All"  "Save All"
	::msgcat::mcset en_us  "Save As"  "Save As"
	::msgcat::mcset en_us  "Save As ..."  "Save As ..."
	::msgcat::mcset en_us  "Save Macro"  "Save Macro"
	::msgcat::mcset en_us  "Search Files..."  "Search Files..."
	::msgcat::mcset en_us  "Search In Files..."  "Search In Files..."
	::msgcat::mcset en_us  "Select All"  "Select All"
	::msgcat::mcset en_us  "Set ' %s ' As Default Script" "Set ' %s ' As Default Script"
	::msgcat::mcset en_us  "Settings..."  "Settings..."
	# New
	::msgcat::mcset en_us  "Shallow" "Shallow"
	::msgcat::mcset en_us  "Show Line Number"  "Show Line Number"
	# New
	::msgcat::mcset en_us  "Show Syntax Helper" "Show Syntax Helper"
	# New
	::msgcat::mcset en_us  "Step" "Step"
	# New
	::msgcat::mcset en_us  "Stop" "Stop"
	::msgcat::mcset en_us  "Syntax Check..." "Syntax Check..."
	::msgcat::mcset en_us  "Syntax Highlight"  "Syntax Highlight"
	::msgcat::mcset en_us  "Tasks"  "Tasks"
	# New
	::msgcat::mcset en_us  "Test" "Test"
	::msgcat::mcset en_us  "Test(W)"  "Test(W)"
	::msgcat::mcset en_us  "The settings will apply at restart CrowTDE!"  "The settings will apply at restart CrowTDE!"
	::msgcat::mcset en_us  "Toolbar Details"  "Toolbar Details"
	::msgcat::mcset en_us  "Tools(T)"  "Tools(T)"
	::msgcat::mcset en_us  "UnIndent Selection"  "UnIndent Selection"
	::msgcat::mcset en_us  "Undo"  "Undo"
	::msgcat::mcset en_us  "Version Control*"  "Version Control*"
	::msgcat::mcset en_us  "Window"  "Window"
	# New
	::msgcat::mcset en_us  "error!" "error!"
	::msgcat::mcset en_us  "freewrap*"  "freewrap*"
}

namespace eval ::fmeNagelfar {
	::msgcat::mcset en_us  "Choose File" "Choose File"
	::msgcat::mcset en_us  "Clear" "Clear"
	# New
	::msgcat::mcset en_us  "Do Check" "Do Check"
	::msgcat::mcset en_us  "File:" "File:"
	::msgcat::mcset en_us  "Save" "Save"
	::msgcat::mcset en_us  "Save Output..." "Save Output..."
	# New
	::msgcat::mcset en_us  "Select File" "Select File"
	# New
	::msgcat::mcset en_us  "Select File..." "Select File..."
}

namespace eval ::fmePlayer {
	::msgcat::mcset en_us  "MP3 Folder"  "MP3 Folder"
	::msgcat::mcset en_us  "MP3:"  "MP3:"
	::msgcat::mcset en_us  "Vol:"  "Vol:"
}

namespace eval ::fmeProcManager {
	# New
	::msgcat::mcset en_us  "Error" "Error"
	::msgcat::mcset en_us  "Interval"  "Interval"
	# New
	::msgcat::mcset en_us  "Please specify Tcl interpreter first!" "Please specify Tcl interpreter first!"
	::msgcat::mcset en_us  "View"  "View"
}

namespace eval ::fmeProjectManager {
	::msgcat::mcset en_us  "%s Open" "%s Open"
	::msgcat::mcset en_us  "'%s' already exists!" "'%s' already exists!"
	::msgcat::mcset en_us  "'%s' already exists." "'%s' already exists."
	::msgcat::mcset en_us  "'%s' has been deleted from the file system!" "'%s' has been deleted from the file system!"
	::msgcat::mcset en_us  "'%s' not exists!" "'%s' not exists!"
	::msgcat::mcset en_us  "All"  "All"
	::msgcat::mcset en_us  "Are you sure you want to delete '%s' from the file system ?" "Are you sure you want to delete '%s' from the file system ?"
	::msgcat::mcset en_us  "Build..." "Build..."
	::msgcat::mcset en_us  "Cancel" "Cancel"
	::msgcat::mcset en_us  "Check Syntax*"  "Check Syntax*"
	::msgcat::mcset en_us  "Close Project"  "Close Project"
	::msgcat::mcset en_us  "Confirm"  "Confirm"
	::msgcat::mcset en_us  "Copied %s" "Copied %s"
	::msgcat::mcset en_us  "Copy"  "Copy"
	::msgcat::mcset en_us  "Cut"  "Cut"
	::msgcat::mcset en_us  "Cut %s" "Cut %s"
	# New
	::msgcat::mcset en_us  "Debug..." "Debug..."
	::msgcat::mcset en_us  "Default script not exists" "Default script not exists"
	::msgcat::mcset en_us  "Default script not specify!"  "Default script not specify!"
	::msgcat::mcset en_us  "Delete"  "Delete"
	::msgcat::mcset en_us  "Edit"  "Edit"
	::msgcat::mcset en_us  "Error"  "Error"
	::msgcat::mcset en_us  "File Properties..."  "File Properties..."
	::msgcat::mcset en_us  "File copy fail!"  "File copy fail!"
	::msgcat::mcset en_us  "File name invalid." "File name invalid."
	::msgcat::mcset en_us  "Folder"  "Folder"
	::msgcat::mcset en_us  "Folder already exists!"  "Folder already exists!"
	::msgcat::mcset en_us  "Import to : (%s)" "Import to : (%s)"
	::msgcat::mcset en_us  "Location : %s" "Location : %s"
	::msgcat::mcset en_us  "New Folder"  "New Folder"
	::msgcat::mcset en_us  "New Item"  "New Item"
	::msgcat::mcset en_us  "No copy target"  "No copy target"
	::msgcat::mcset en_us  "Ok" "Ok"
	# New
	::msgcat::mcset en_us  "Open" "Open"
	::msgcat::mcset en_us  "Open As..."  "Open As..."
	::msgcat::mcset en_us  "Open Project"  "Open Project"
	::msgcat::mcset en_us  "Others..."  "Others..."
	::msgcat::mcset en_us  "Paste"  "Paste"
	# New
	::msgcat::mcset en_us  "Please specify Tcl or Tk interpreter first!" "Please specify Tcl or Tk interpreter first!"
	::msgcat::mcset en_us  "Project - %s" "Project - %s"
	::msgcat::mcset en_us  "Project Properties..."  "Project Properties..."
	::msgcat::mcset en_us  "Rename"  "Rename"
	::msgcat::mcset en_us  "Rename fail!"  "Rename fail!"
	::msgcat::mcset en_us  "Replace" "Replace"
	::msgcat::mcset en_us  "Run..."  "Run..."
	::msgcat::mcset en_us  "Save Project.."  "Save Project.."
	::msgcat::mcset en_us  "Set As Default Script"  "Set As Default Script"
	::msgcat::mcset en_us  "Syntax Check..." "Syntax Check..."
	::msgcat::mcset en_us  "The folder already contains a file named %s" "The folder already contains a file named %s"
	::msgcat::mcset en_us  "The operation need close current project. Close project ?"  "The operation need close current project. Close project ?"
	::msgcat::mcset en_us  "refresh"  "refresh"
}

namespace eval ::fmeStatusBar {
	::msgcat::mcset en_us  "Lines"  "Lines"
	::msgcat::mcset en_us  "Pos"  "Pos"
}

namespace eval ::fmeTabEditor {
	::msgcat::mcset en_us  "'%s' has not save. save it ?" "'%s' has not save. save it ?"
	::msgcat::mcset en_us  "Cancal"  "Cancal"
	::msgcat::mcset en_us  "Copy %s - %s" "Copy %s - %s"
	::msgcat::mcset en_us  "Cut %s - %s" "Cut %s - %s"
	::msgcat::mcset en_us  "No Copy Region"  "No Copy Region"
	::msgcat::mcset en_us  "No Cut Region"  "No Cut Region"
	::msgcat::mcset en_us  "Paste"  "Paste"
	::msgcat::mcset en_us  "Print"  "Print"
	::msgcat::mcset en_us  "Print Command:"  "Print Command:"
}

namespace eval ::fmeTabMgr {
	# New
	::msgcat::mcset en_us  "Debug" "Debug"
	::msgcat::mcset en_us  "File"  "File"
	::msgcat::mcset en_us  "Help" "Help"
	::msgcat::mcset en_us  "Proc"  "Proc"
}

namespace eval ::fmeTask {
	::msgcat::mcset en_us  "Add Task"  "Add Task"
	# New
	::msgcat::mcset en_us  "All" "All"
	# New
	::msgcat::mcset en_us  "Are you sure you want to delete %%d tasks?" "Are you sure you want to delete %%d tasks?"
	# New
	::msgcat::mcset en_us  "Change State" "Change State"
	::msgcat::mcset en_us  "Delete"  "Delete"
	::msgcat::mcset en_us  "Delete Completed Tasks"  "Delete Completed Tasks"
	::msgcat::mcset en_us  "Delete Task"  "Delete Task"
	::msgcat::mcset en_us  "Description"  "Description"
	::msgcat::mcset en_us  "Do you want to delete completed task ?"  "Do you want to delete completed task ?"
	::msgcat::mcset en_us  "Do you want to delete task ?"  "Do you want to delete task ?"
	::msgcat::mcset en_us  "Edit"  "Edit"
	# New
	::msgcat::mcset en_us  "Find" "Find"
	# New
	::msgcat::mcset en_us  "Finished" "Finished"
	# New
	::msgcat::mcset en_us  "Hide Completed Tasks" "Hide Completed Tasks"
	# New
	::msgcat::mcset en_us  "In Progress" "In Progress"
	# New
	::msgcat::mcset en_us  "Not Started" "Not Started"
	::msgcat::mcset en_us  "Refresh"  "Refresh"
	# New
	::msgcat::mcset en_us  "Reset" "Reset"
	# New
	::msgcat::mcset en_us  "Search:" "Search:"
	::msgcat::mcset en_us  "State"  "State"
	::msgcat::mcset en_us  "Task Delete"  "Task Delete"
	# New
	::msgcat::mcset en_us  "Task already hidden!" "Task already hidden!"
	::msgcat::mcset en_us  "Time"  "Time"
}

namespace eval ::fmeTaskMgr {
	# New
	::msgcat::mcset en_us  "Debug" "Debug"
	::msgcat::mcset en_us  "Nagelfar" "Nagelfar"
	::msgcat::mcset en_us  "Tasks"  "Tasks"
	::msgcat::mcset en_us  "TkCon"  "TkCon"
}

namespace eval ::fmeToolbar {
	::msgcat::mcset en_us  "Add Block Comment"  "Add Block Comment"
	::msgcat::mcset en_us  "Backward"  "Backward"
	::msgcat::mcset en_us  "Case Sensitive"  "Case Sensitive"
	::msgcat::mcset en_us  "Copy"  "Copy"
	::msgcat::mcset en_us  "Cut"  "Cut"
	# New
	::msgcat::mcset en_us  "Debug Default Script..." "Debug Default Script..."
	# New
	::msgcat::mcset en_us  "Debug current file" "Debug current file"
	# New
	::msgcat::mcset en_us  "Debug project" "Debug project"
	# New
	::msgcat::mcset en_us  "Debug..." "Debug..."
	::msgcat::mcset en_us  "File..."  "File..."
	::msgcat::mcset en_us  "Find"  "Find"
	::msgcat::mcset en_us  "Find Options"  "Find Options"
	::msgcat::mcset en_us  "Folder..."  "Folder..."
	::msgcat::mcset en_us  "Ident Selection"  "Ident Selection"
	::msgcat::mcset en_us  "MP3 Player" "MP3 Player"
	::msgcat::mcset en_us  "New"  "New"
	::msgcat::mcset en_us  "Open"  "Open"
	::msgcat::mcset en_us  "Open File"  "Open File"
	::msgcat::mcset en_us  "Paste"  "Paste"
	::msgcat::mcset en_us  "Print current editor..." "Print current editor..."
	::msgcat::mcset en_us  "Project..."  "Project..."
	::msgcat::mcset en_us  "Redo"  "Redo"
	::msgcat::mcset en_us  "Regular Expression"  "Regular Expression"
	::msgcat::mcset en_us  "Remove Block Comment"  "Remove Block Comment"
	::msgcat::mcset en_us  "Run Project..."  "Run Project..."
	::msgcat::mcset en_us  "Run..."  "Run..."
	::msgcat::mcset en_us  "Save"  "Save"
	::msgcat::mcset en_us  "Save All"  "Save All"
	::msgcat::mcset en_us  "Search files" "Search files"
	::msgcat::mcset en_us  "Search in files" "Search in files"
	# New
	::msgcat::mcset en_us  "Start Debugger" "Start Debugger"
	# New
	::msgcat::mcset en_us  "Stop" "Stop"
	# New
	::msgcat::mcset en_us  "Stop '%s'" "Stop '%s'"
	::msgcat::mcset en_us  "Syntax check..." "Syntax check..."
	::msgcat::mcset en_us  "UnIdent Selection"  "UnIdent Selection"
	::msgcat::mcset en_us  "Undo"  "Undo"
}

namespace eval ::frmAbout {
	::msgcat::mcset en_us  "About CrowTDE"  "About CrowTDE"
	# New
	::msgcat::mcset en_us  "Copyright (C) 2006-2007 Tai, Yuan-Liang & Zheng, Shao-Huan" "Copyright (C) 2006-2007 Tai, Yuan-Liang & Zheng, Shao-Huan"
	# New
	::msgcat::mcset en_us  "Credits" "Credits"
	# New
	::msgcat::mcset en_us  "CrowTDE License" "CrowTDE License"
	# New
	::msgcat::mcset en_us  "CrowTDE is an open source Tcl/Tk development %s environment written in Tcl/Tk. Its purposes is to provide a %s convenient environment for Tcl/Tk programmers." "CrowTDE is an open source Tcl/Tk development %s environment written in Tcl/Tk. Its purposes is to provide a %s convenient environment for Tcl/Tk programmers."
	# New
	::msgcat::mcset en_us  "Exit" "Exit"
	# New
	::msgcat::mcset en_us  "German - Michael Schlenker <mic42@user.sourceforge.net> %s" "German - Michael Schlenker <mic42@user.sourceforge.net> %s"
	# New
	::msgcat::mcset en_us  "Italian - Diego <siarodx@gmail.com> %s" "Italian - Diego <siarodx@gmail.com> %s"
	# New
	::msgcat::mcset en_us  "License" "License"
	# New
	::msgcat::mcset en_us  "License:" "License:"
	# New
	::msgcat::mcset en_us  "Traditional Chinese - Zang, Ke-Yuan <jarry@crow.ee.stut.edu.tw> %s" "Traditional Chinese - Zang, Ke-Yuan <jarry@crow.ee.stut.edu.tw> %s"
	# New
	::msgcat::mcset en_us  "Translators" "Translators"
	# New
	::msgcat::mcset en_us  "Visit : http://crow.ee.stut.edu.tw/dai/crowtde/" "Visit : http://crow.ee.stut.edu.tw/dai/crowtde/"
}

namespace eval ::frmCheckSave {
	::msgcat::mcset en_us  "Cancel"  "Cancel"
	::msgcat::mcset en_us  "No"  "No"
	::msgcat::mcset en_us  "Save"  "Save"
	::msgcat::mcset en_us  "Save files ?" "Save files ?"
	::msgcat::mcset en_us  "Yes"  "Yes"
}

namespace eval ::frmFirst {
	::msgcat::mcset en_us  "Basic Settings"  "Basic Settings"
	::msgcat::mcset en_us  "Browse..."  "Browse..."
	::msgcat::mcset en_us  "Information"  "Information"
	::msgcat::mcset en_us  "Language:"  "Language:"
	::msgcat::mcset en_us  "Ok"  "Ok"
	::msgcat::mcset en_us  "Open File"  "Open File"
	::msgcat::mcset en_us  "Tcl Interpreter:"  "Tcl Interpreter:"
	::msgcat::mcset en_us  "Tk Interpreter:"  "Tk Interpreter:"
	::msgcat::mcset en_us  "You are first time running CrowTDE.%s Please configure your basic run-time environment." "You are first time running CrowTDE.%s Please configure your basic run-time environment."
	::msgcat::mcset en_us  "You can configure more details from 'Main Menu->Options->Settings' ."  "You can configure more details from 'Main Menu->Options->Settings' ."
}

namespace eval ::frmNewProject {
	::msgcat::mcset en_us  "'%s' already exists." "'%s' already exists."
	::msgcat::mcset en_us  "Browse..."  "Browse..."
	::msgcat::mcset en_us  "Cancel"  "Cancel"
	::msgcat::mcset en_us  "Create"  "Create"
	::msgcat::mcset en_us  "Default Script:"  "Default Script:"
	::msgcat::mcset en_us  "Error"  "Error"
	::msgcat::mcset en_us  "Interpreter"  "Interpreter"
	::msgcat::mcset en_us  "Interpreter:"  "Interpreter:"
	::msgcat::mcset en_us  "New Project"  "New Project"
	::msgcat::mcset en_us  "Please choose template first!"  "Please choose template first!"
	::msgcat::mcset en_us  "Project Name:"  "Project Name:"
	::msgcat::mcset en_us  "Template:"  "Template:"
	::msgcat::mcset en_us  "Workspace"  "Workspace"
	::msgcat::mcset en_us  "Workspace:"  "Workspace:"
}

namespace eval ::frmProjectProperty {
	::msgcat::mcset en_us  "Browse..."  "Browse..."
	::msgcat::mcset en_us  "Cancel"  "Cancel"
	::msgcat::mcset en_us  "Default Script:"  "Default Script:"
	::msgcat::mcset en_us  "Interpreter"  "Interpreter"
	::msgcat::mcset en_us  "Interpreter:"  "Interpreter:"
	::msgcat::mcset en_us  "Ok"  "Ok"
	::msgcat::mcset en_us  "Project Name:"  "Project Name:"
	::msgcat::mcset en_us  "Project Properties"  "Project Properties"
	::msgcat::mcset en_us  "Workspace:"  "Workspace:"
}

namespace eval ::frmSearchFiles {
	::msgcat::mcset en_us  "Browse..."  "Browse..."
	::msgcat::mcset en_us  "Choose Directory"  "Choose Directory"
	::msgcat::mcset en_us  "Directory:"  "Directory:"
	::msgcat::mcset en_us  "Error"  "Error"
	::msgcat::mcset en_us  "File name:"  "File name:"
	::msgcat::mcset en_us  "Finish %s items found." "Finish %s items found."
	::msgcat::mcset en_us  "Keyword can't empty!"  "Keyword can't empty!"
	::msgcat::mcset en_us  "Search directory not valid!"  "Search directory not valid!"
	::msgcat::mcset en_us  "Search files" "Search files"
	::msgcat::mcset en_us  "Search hidden files & folders"  "Search hidden files & folders"
	::msgcat::mcset en_us  "Start"  "Start"
	::msgcat::mcset en_us  "Stop"  "Stop"
}

namespace eval ::frmSearchInFiles {
	::msgcat::mcset en_us  "Browse..."  "Browse..."
	::msgcat::mcset en_us  "Case Sensitive"  "Case Sensitive"
	::msgcat::mcset en_us  "Choose Directory"  "Choose Directory"
	::msgcat::mcset en_us  "Directory"  "Directory"
	::msgcat::mcset en_us  "Error"  "Error"
	::msgcat::mcset en_us  "Filter:"  "Filter:"
	::msgcat::mcset en_us  "Keyword can't empty!"  "Keyword can't empty!"
	::msgcat::mcset en_us  "Keyword:"  "Keyword:"
	::msgcat::mcset en_us  "Regular Expression"  "Regular Expression"
	::msgcat::mcset en_us  "Search directory not valid!"  "Search directory not valid!"
	::msgcat::mcset en_us  "Search hidden files & folders"  "Search hidden files & folders"
	::msgcat::mcset en_us  "Search in files" "Search in files"
	::msgcat::mcset en_us  "Start"  "Start"
	::msgcat::mcset en_us  "Stop"  "Stop"
}

namespace eval ::frmSetting {
	# New
	::msgcat::mcset en_us  "CrowTDE configuration" "CrowTDE configuration"
	::msgcat::mcset en_us  "Editor Settings" "Editor Settings"
	::msgcat::mcset en_us  "Exit"  "Exit"
	::msgcat::mcset en_us  "File Settings" "File Settings"
	::msgcat::mcset en_us  "Fonts"  "Fonts"
	::msgcat::mcset en_us  "General"  "General"
}

namespace eval ::frmStartPage {
	::msgcat::mcset en_us  "Browse..."  "Browse..."
	::msgcat::mcset en_us  "Cancel"  "Cancel"
	::msgcat::mcset en_us  "Create New Project..."  "Create New Project..."
	::msgcat::mcset en_us  "CrowTDE Start Page"  "CrowTDE Start Page"
	::msgcat::mcset en_us  "Ok"  "Ok"
	::msgcat::mcset en_us  "Open Last Project (%s)" "Open Last Project (%s)"
	::msgcat::mcset en_us  "Open Project"  "Open Project"
	::msgcat::mcset en_us  "Please Choose Function"  "Please Choose Function"
	::msgcat::mcset en_us  "Project:"  "Project:"
}

namespace eval ::svnWrapper {
	# New
	::msgcat::mcset en_us  "...ok!" "...ok!"
	# New
	::msgcat::mcset en_us  "Add" "Add"
	# New
	::msgcat::mcset en_us  "Are you want to remove '%s' propeties?" "Are you want to remove '%s' propeties?"
	# New
	::msgcat::mcset en_us  "Cancel" "Cancel"
	# New
	::msgcat::mcset en_us  "Check for modifications" "Check for modifications"
	# New
	::msgcat::mcset en_us  "Checkout" "Checkout"
	# New
	::msgcat::mcset en_us  "Checkout directory:" "Checkout directory:"
	# New
	::msgcat::mcset en_us  "Checkout from SVN" "Checkout from SVN"
	# New
	::msgcat::mcset en_us  "Choose Directory" "Choose Directory"
	# New
	::msgcat::mcset en_us  "Clean up" "Clean up"
	# New
	::msgcat::mcset en_us  "Commit" "Commit"
	# New
	::msgcat::mcset en_us  "Commit to : %s" "Commit to : %s"
	# New
	::msgcat::mcset en_us  "Delete" "Delete"
	# New
	::msgcat::mcset en_us  "Directory can't empty." "Directory can't empty."
	# New
	::msgcat::mcset en_us  "Directory:" "Directory:"
	# New
	::msgcat::mcset en_us  "Edit" "Edit"
	# New
	::msgcat::mcset en_us  "Error!" "Error!"
	# New
	::msgcat::mcset en_us  "Export" "Export"
	# New
	::msgcat::mcset en_us  "Export: %s" "Export: %s"
	# New
	::msgcat::mcset en_us  "File list is empty!" "File list is empty!"
	# New
	::msgcat::mcset en_us  "HEAD revision" "HEAD revision"
	# New
	::msgcat::mcset en_us  "Import" "Import"
	# New
	::msgcat::mcset en_us  "Import Message:" "Import Message:"
	# New
	::msgcat::mcset en_us  "Include ignored files" "Include ignored files"
	# New
	::msgcat::mcset en_us  "Include unversion file(s)" "Include unversion file(s)"
	# New
	::msgcat::mcset en_us  "Login" "Login"
	# New
	::msgcat::mcset en_us  "Message : " "Message : "
	# New
	::msgcat::mcset en_us  "Move" "Move"
	# New
	::msgcat::mcset en_us  "Move to:" "Move to:"
	# New
	::msgcat::mcset en_us  "No files were changed or added since the last commit." "No files were changed or added since the last commit."
	# New
	::msgcat::mcset en_us  "Not thing to do." "Not thing to do."
	# New
	::msgcat::mcset en_us  "Ok" "Ok"
	# New
	::msgcat::mcset en_us  "Passwd:" "Passwd:"
	# New
	::msgcat::mcset en_us  "Please select a property first!" "Please select a property first!"
	# New
	::msgcat::mcset en_us  "Please wait" "Please wait"
	# New
	::msgcat::mcset en_us  "Properties" "Properties"
	# New
	::msgcat::mcset en_us  "Property" "Property"
	# New
	::msgcat::mcset en_us  "Property :" "Property :"
	# New
	::msgcat::mcset en_us  "Remove" "Remove"
	# New
	::msgcat::mcset en_us  "Remove properties" "Remove properties"
	# New
	::msgcat::mcset en_us  "Rename" "Rename"
	# New
	::msgcat::mcset en_us  "Repository:" "Repository:"
	# New
	::msgcat::mcset en_us  "Resolved" "Resolved"
	# New
	::msgcat::mcset en_us  "Revert" "Revert"
	# New
	::msgcat::mcset en_us  "Revision" "Revision"
	# New
	::msgcat::mcset en_us  "SVN Update" "SVN Update"
	# New
	::msgcat::mcset en_us  "Status" "Status"
	# New
	::msgcat::mcset en_us  "Subversion" "Subversion"
	# New
	::msgcat::mcset en_us  "Svn" "Svn"
	# New
	::msgcat::mcset en_us  "Target : %s" "Target : %s"
	# New
	::msgcat::mcset en_us  "URL can't empty." "URL can't empty."
	# New
	::msgcat::mcset en_us  "URL of repository:" "URL of repository:"
	# New
	::msgcat::mcset en_us  "Update" "Update"
	# New
	::msgcat::mcset en_us  "Username:" "Username:"
	# New
	::msgcat::mcset en_us  "Value" "Value"
	# New
	::msgcat::mcset en_us  "Value :" "Value :"
	# New
	::msgcat::mcset en_us  "error" "error"
	# New
	::msgcat::mcset en_us  "update" "update"
}

namespace eval ::crowTemplate {
	#New
	::msgcat::mcset zh_tw "Empty file" "Empty file"
	#New
	::msgcat::mcset zh_tw "Tcl Package" "Tcl Package"
	
	#New
	::msgcat::mcset zh_tw "Create an empty project." "Create an empty project."	
	# New
	::msgcat::mcset zh_tw  "Checkout project from SVN Repository." "Checkout project from SVN Repository."
	# New
	::msgcat::mcset zh_tw  "SVN Project" "SVN Project"
}
