namespace eval ::crowDebugger {
	# New
	::msgcat::mcset it_it  "...abort" "...annulla"
	# New
	::msgcat::mcset it_it  "...ok" "...ok"
	# New
	::msgcat::mcset it_it  "Debug script is not specified or not exists.!" "Lo script di debug non è stato specificato o non esiste.!"
	# New
	::msgcat::mcset it_it  "Debugger already running!" "Il debugger è già eseguito!"
	# New
	::msgcat::mcset it_it  "Debugger has not started!" "Il debugger non è stato eseguito!"
	# New
	::msgcat::mcset it_it  "Error" "Errore"
	# New
	::msgcat::mcset it_it  "Interpreter is not specified or not exists!" "L'interprete non è stato specificato o non esiste!"
	# New
	::msgcat::mcset it_it  "Loading '%s' ..." "Avvio '%s' ..."
	# New
	::msgcat::mcset it_it  "Start Debugger...ok" "Avvia debugger...ok"
	# New
	::msgcat::mcset it_it  "Stop Debugger....ok" "Avvia debugger....ok"
	# New
	::msgcat::mcset it_it  "error" "errore"
}

namespace eval ::crowEditor {
	::msgcat::mcset it_it  "'%s' has been delete from the file system. Save it?" "'%s' è stato cancellato dal file system. Salvarlo?"
	::msgcat::mcset it_it  "'%s' has been deleted from the file system. Save ?" "'%s' è stato cancellato dal file system. Salvare ?"
	::msgcat::mcset it_it  "'%s' has been modified. Reload file ?" "'%s' è stato modificato. Ricaricare il file ?"
	::msgcat::mcset it_it  "'%s' has been modified. Save changes ?" "'%s' è stato modificato. Salvare le modifiche ?"
	::msgcat::mcset it_it  "Add Block Comment"  "Aggiungi Blocco Commento"
	::msgcat::mcset it_it  "Backward"  "All'indietro"
	::msgcat::mcset it_it  "Case Sensitive"  "Rispetta Maiuscole/Minuscole"
	::msgcat::mcset it_it  "Colors"  "Colori"
	::msgcat::mcset it_it  "Comment:"  "Commento:"
	::msgcat::mcset it_it  "Copy"  "Copia"
	::msgcat::mcset it_it  "Cut"  "Taglia"
	::msgcat::mcset it_it  "Cut Line"  "Taglia Linea"
	::msgcat::mcset it_it  "Cut word"  "Taglia parola"
	::msgcat::mcset it_it  "Default disabled"  "Disabilitato Come Predefinito"
	::msgcat::mcset it_it  "Default enabled"  "Abilitato Come Predefinito"
	::msgcat::mcset it_it  "Delete"  "Rimuovi"
	::msgcat::mcset it_it  "Editor Settings" "Impostazioni Editor"
	::msgcat::mcset it_it  "Exit"  "Uscita"
	::msgcat::mcset it_it  "Find"  "Trova"
	::msgcat::mcset it_it  "Find And Replace"  "Trova e Sostituisci"
	::msgcat::mcset it_it  "Find Next"  "Trova Successivo"
	::msgcat::mcset it_it  "Find/Replace..."  "Trova/Sostituisci..."
	::msgcat::mcset it_it  "Indent Selection"  "Indenta Selezione"
	::msgcat::mcset it_it  "Information"  "Informazioni"
	::msgcat::mcset it_it  "Information!" "Information!"
	::msgcat::mcset it_it  "Insert Macro"  "Inserisci Macro"
	::msgcat::mcset it_it  "Items"  "Elementi"
	::msgcat::mcset it_it  "Jump To"  "Salta A"
	::msgcat::mcset it_it  "Jump To..."  "Salta A..."
	::msgcat::mcset it_it  "Numerical:"  "Numerico:"
	::msgcat::mcset it_it  "Paste"  "Incolla"
	::msgcat::mcset it_it  "Redo"  "Ripeto"
	::msgcat::mcset it_it  "Regular expression"  "Espressione regolare"
	::msgcat::mcset it_it  "Remove Block Comment"  "Rimuovi Blocco Commento"
	::msgcat::mcset it_it  "Repalce All"  "Sostituisci Tutto"
	::msgcat::mcset it_it  "Replace"  "Sostituisci"
	::msgcat::mcset it_it  "Reset"  "Riavvia"
	::msgcat::mcset it_it  "Save"  "Salva"
	::msgcat::mcset it_it  "Save File"  "Salva File"
	::msgcat::mcset it_it  "Save Macro"  "Salva Macro"
	::msgcat::mcset it_it  "Save file!"  "Salva file!"
	::msgcat::mcset it_it  "Save success"  "Salvato con successo"
	::msgcat::mcset it_it  "Select All"  "Seleziona Tutto"
	::msgcat::mcset it_it  "Select Line"  "Selezione Linea"
	::msgcat::mcset it_it  "Select word"  "Seleziona parola"
	::msgcat::mcset it_it  "Set Breakpoint" "Imposta Breakpoint"
	::msgcat::mcset it_it  "String Not Found"  "Stringa Non Trovata"
	::msgcat::mcset it_it  "String:"  "Stringa:"
	::msgcat::mcset it_it  "Syntax Highlight"  "Evidenzia Sintassi"
	::msgcat::mcset it_it  "Tab width" "Larghezza tab"
	::msgcat::mcset it_it  "Tcl Argument:" "Argomenti Tcl:"
	::msgcat::mcset it_it  "Tcl Command:" "Comando Tcl:"
	::msgcat::mcset it_it  "Tk Argument:" "Argomenti Tk:"
	::msgcat::mcset it_it  "Tk Command:" "Comando Tk:"
	::msgcat::mcset it_it  "Undo"  "Annulla"
	::msgcat::mcset it_it  "Unindent Selection"  "DeIndenta Selezione"
	::msgcat::mcset it_it  "Unset Breakpoint" "Disimposta Breakpoint"
	::msgcat::mcset it_it  "Variable:"  "Variabile:"
	::msgcat::mcset it_it  "Warring!"  "Attenzione!"
}

namespace eval ::crowExec {
	::msgcat::mcset it_it  "%s...Exit" "%s...Uscita"
	::msgcat::mcset it_it  "Error" "Errore"
	::msgcat::mcset it_it  "Interpreter '%s' not exists" "L'interprete '%s' non esiste"
	::msgcat::mcset it_it  "Permission denied" "Permesso negato"
	::msgcat::mcset it_it  "Run %s..." "Esegui %s..."
	::msgcat::mcset it_it  "You may not permission to execuate this file! Execuate force?" "Non dovresti avere il permesso di eseguire questo file! Forzare l'esecuzione?"
}

namespace eval ::crowFileProperties {
	::msgcat::mcset it_it  "Accept" "Accetta"
	::msgcat::mcset it_it  "Accessed:" "Accesso:"
	::msgcat::mcset it_it  "Cancel" "Cancella"
	::msgcat::mcset it_it  "Changed:" "Cambiato:"
	::msgcat::mcset it_it  "File Properties" "Proprietà File"
	::msgcat::mcset it_it  "General" "Generale"
	::msgcat::mcset it_it  "Group" "Gruppo"
	::msgcat::mcset it_it  "Location:" "Locazione:"
	::msgcat::mcset it_it  "Modified:" "Modificato:"
	::msgcat::mcset it_it  "Name:" "Nome:"
	::msgcat::mcset it_it  "Other" "Altri"
	::msgcat::mcset it_it  "Owner" "Proprietario"
	::msgcat::mcset it_it  "Permissions" "Permessi"
	::msgcat::mcset it_it  "Read" "Leggi"
	::msgcat::mcset it_it  "SID" "SID"
	::msgcat::mcset it_it  "Set GID" "Set GID"
	::msgcat::mcset it_it  "Set UID" "Set UID"
	::msgcat::mcset it_it  "Size:" "Dimensione:"
	::msgcat::mcset it_it  "Type:" "Tipo:"
	::msgcat::mcset it_it  "Write" "Scrittura"
	::msgcat::mcset it_it  "execute" "esecuzione"
	::msgcat::mcset it_it  "recursive apply" "applica ricorsivamente"
}

namespace eval ::crowFileRelation {
	::msgcat::mcset it_it  "Add"  "Aggiungi"
	::msgcat::mcset it_it  "All"  "Tutto"
	::msgcat::mcset it_it  "Application"  "Applicazione"
	::msgcat::mcset it_it  "Application:" "Applicazione:"
	::msgcat::mcset it_it  "Browse..."  "Sfoglia..."
	::msgcat::mcset it_it  "File Extension:" "Estensione File:"
	::msgcat::mcset it_it  "File Relation Setting"  "Impostazioni File"
	::msgcat::mcset it_it  "File types"  "Tipi File"
	::msgcat::mcset it_it  "Remove"  "Rimuovi"
	::msgcat::mcset it_it  "Setting default"  "Impostazioni predefinite"
}

namespace eval ::crowFont {
	::msgcat::mcset it_it  "Apply"  "Applica"
	::msgcat::mcset it_it  "Editor font"  "Editor font"
	::msgcat::mcset it_it  "Fonts setting"  "Impostazioni fonts"
	::msgcat::mcset it_it  "Large font"  "Font grande"
	::msgcat::mcset it_it  "Menu font"  "Menu font"
	::msgcat::mcset it_it  "Small font"  "Font piccolo"
	::msgcat::mcset it_it  "normal font"  "Font medio"
}

namespace eval ::crowGetDir {
	::msgcat::mcset it_it  "'%s' has been deleted from the file system!" "'%s' è stato cancellato dal file system!"
	::msgcat::mcset it_it  "Cancel" "Cancella"
	::msgcat::mcset it_it  "Choose Direcotry" "Scegli Cartella"
	::msgcat::mcset it_it  "Choose Folder First!" "Scegli Prima Una Cartella!"
	::msgcat::mcset it_it  "Error" "Errore"
	::msgcat::mcset it_it  "Folder Already Exists!" "La Cartella Esiste Già!"
	::msgcat::mcset it_it  "New Folder" "Nuova Cartella"
	::msgcat::mcset it_it  "Ok" "Ok"
}

namespace eval ::crowIO {
	::msgcat::mcset it_it  "Cancel"  "Cancella"
	::msgcat::mcset it_it  "Ok" "Ok"
	::msgcat::mcset it_it  "Wrong argument!"  "Argomento sbagliato!"
	::msgcat::mcset it_it  "gets" "prendi"
	::msgcat::mcset it_it  "read" "leggi"
}

namespace eval ::crowMacro {
	::msgcat::mcset it_it  "--Delete This Folder--" "--Cancella Questa Cartella--"
	::msgcat::mcset it_it  "Are you sure you want to delete macro?"  "Sei sicuro di voler cancellare la macro?"
	::msgcat::mcset it_it  "Browse" "Sfoglia"
	::msgcat::mcset it_it  "Cancel"  "Cancella"
	::msgcat::mcset it_it  "Codes:" "Codici:"
	::msgcat::mcset it_it  "Delete"  "Rimuovi"
	::msgcat::mcset it_it  "Macro Name:" "Nome Macro:"
	::msgcat::mcset it_it  "Ok"  "Ok"
	::msgcat::mcset it_it  "Operations"  "Operazioni"
	::msgcat::mcset it_it  "Save Macro"  "Salva Macro"
	::msgcat::mcset it_it  "Save Path:"  "Percorso di salvataggio:"
	::msgcat::mcset it_it  "System Define"  "Definito dal sistema"
	::msgcat::mcset it_it  "User Define"  "Definito dall'utente"
}

namespace eval ::crowRC {
	::msgcat::mcset it_it  "Create fail!"  "Creazione fallita!"
	::msgcat::mcset it_it  "Error"  "Errore"
}

namespace eval ::crowSdx {
	::msgcat::mcset it_it  "%s Elapsed time ... %02s:%02s" "%s Tempo Trascorso ... %02s:%02s"
	::msgcat::mcset it_it  "Browse" "Sfoglia"
	::msgcat::mcset it_it  "Building starkit ..." "Costruisco starkit ..."
	::msgcat::mcset it_it  "Cancel" "Cancella"
	::msgcat::mcset it_it  "Do not compress files added to starkit" "Non comprimere i files aggiunti allo starkit"
	::msgcat::mcset it_it  "Finish." "Finito."
	::msgcat::mcset it_it  "Move '%s' -> '%s'" "Muovi '%s' -> '%s'"
	::msgcat::mcset it_it  "Ok" "Ok"
	::msgcat::mcset it_it  "Options" "Opzioni"
	::msgcat::mcset it_it  "SDX" "SDX"
	::msgcat::mcset it_it  "Save As.." "Salva Come.."
	::msgcat::mcset it_it  "Save to:" "Salva su:"
	::msgcat::mcset it_it  "Script:" "Script:"
	::msgcat::mcset it_it  "Size = %s (KB)" "Dimensione = %s (KB)"
	::msgcat::mcset it_it  "Starkit runtime not exists!" "Starkit runtime non esiste!"
	::msgcat::mcset it_it  "VFS Directory:" "VFS Cartella:"
	::msgcat::mcset it_it  "Writable" "Scrivibile"
	::msgcat::mcset it_it  "error" "errore"
	::msgcat::mcset it_it  "include runtime" "includi runtime"
}

namespace eval ::crowSyntax {
	::msgcat::mcset it_it  "Cancel" "Cancella"
	::msgcat::mcset it_it  "Ok" "Ok"
}

namespace eval ::crowTde {
	::msgcat::mcset it_it  "CrowTDE Start success, thanks for use ^o^"  "CrowTDE Avviato con successo, grazie per l'uso ^o^"
	# New
	::msgcat::mcset it_it  "Loading plugin '%s' ..." "Loading plugin '%s' ..."
}

namespace eval ::crowThread {
	::msgcat::mcset it_it  "%s Finish" "%s Finito"
	::msgcat::mcset it_it  "Error"  "Errore"
	::msgcat::mcset it_it  "Interpreter '%s' not exists" "L'interprete '%s' non esiste"
	::msgcat::mcset it_it  "Permission denied" "Permesso negato"
	::msgcat::mcset it_it  "Run %s ..." "Avvia %s ..."
	::msgcat::mcset it_it  "You may not permission to execuate this file! Execuate force?" "Non dovresti avere il permesso di eseguire questo file! Forzare l'esecuzione?"
}

namespace eval ::fmeDebugger {
	::msgcat::mcset it_it  "Add Watch" "Add Watch"
	::msgcat::mcset it_it  "Add Watch..." "Aggiungi Watch..."
	::msgcat::mcset it_it  "Breakpoints" "Breakpoints"
	::msgcat::mcset it_it  "Change Value..." "Cambia Valore..."
	::msgcat::mcset it_it  "Change value" "Cambia valore"
	::msgcat::mcset it_it  "Currently-Visible Variables" "Variabili correntemente visibili"
	::msgcat::mcset it_it  "Debug" "Debug"
	::msgcat::mcset it_it  "Debug Default Script..." "Debug Default Script..."
	::msgcat::mcset it_it  "Debug level" "Livello di debug"
	::msgcat::mcset it_it  "Debug..." "Debug..."
	::msgcat::mcset it_it  "Deep" "Accurato"
	::msgcat::mcset it_it  "Free go" "Free go"
	::msgcat::mcset it_it  "Info" "Info"
	::msgcat::mcset it_it  "Lines:" "Linee:"
	::msgcat::mcset it_it  "Normal" "Normale"
	::msgcat::mcset it_it  "Pause" "Pausa"
	::msgcat::mcset it_it  "Position:" "Posizione:"
	::msgcat::mcset it_it  "Remove" "Rimuovi"
	::msgcat::mcset it_it  "Remove Watch" "Rimuovi Watch"
	::msgcat::mcset it_it  "Script:" "Script:"
	::msgcat::mcset it_it  "Shallow" "Superficiale"
	::msgcat::mcset it_it  "Start Debugger" "Avvia Debugger"
	::msgcat::mcset it_it  "Step" "Fase"
	::msgcat::mcset it_it  "Stop debugging" "Ferma debugging"
	::msgcat::mcset it_it  "View" "Visualizza"
	::msgcat::mcset it_it  "Watch Variables" "Variabili Watch"
	::msgcat::mcset it_it  "Watchpoint already exists!" "Punto di Watch esiste già!"
}

namespace eval ::fmeDocView {
	::msgcat::mcset it_it  "Collapse" "Piega"
	::msgcat::mcset it_it  "Copy" "Copia"
	::msgcat::mcset it_it  "Copy %d %s" "Copia %d %s"
	::msgcat::mcset it_it  "Document Viewer(%s)" "Visualizzatore di Documenti(%s)"
	::msgcat::mcset it_it  "Home" "Home"
	::msgcat::mcset it_it  "Next" "Successivo"
	::msgcat::mcset it_it  "Previous" "Precedente"
	::msgcat::mcset it_it  "Top" "Cima"
	::msgcat::mcset it_it  "View in new window" "Visualizza in una nuova finestra"
}

namespace eval ::fmeGenericSetting {
	::msgcat::mcset it_it  "Browse..."  "Sfoglia..."
	::msgcat::mcset it_it  "Choose Tcl interpreter"  "Scegli l'interprete Tcl"
	::msgcat::mcset it_it  "Choose Tk interpreter"  "Scegli l'interprete Tk"
	::msgcat::mcset it_it  "Create new project"  "Crea nuovo progetto"
	::msgcat::mcset it_it  "Debug Level" "Livello di Debug"
	::msgcat::mcset it_it  "Deep" "Accurato"
	::msgcat::mcset it_it  "Do nothing"  "Non fare nulla"
	::msgcat::mcset it_it  "General Settings"  "Impostazioni Generali"
	::msgcat::mcset it_it  "Interpreter"  "Interprete"
	::msgcat::mcset it_it  "Normal" "Normale"
	::msgcat::mcset it_it  "Open last edit project"  "Apri l'ultimo progetto modificato"
	::msgcat::mcset it_it  "Shallow" "Superficiale"
	::msgcat::mcset it_it  "Show startup page"  "Mostra pagina di avvio"
	::msgcat::mcset it_it  "Startup"  "Avvio"
	::msgcat::mcset it_it  "Tcl Interpreter:"  "Interprete Tcl:"
	::msgcat::mcset it_it  "Tk Interpreter:"  "Interprete Tk:"
}

namespace eval ::fmeMenuBar {
	::msgcat::mcset it_it  "About..."  "Riguardo a..."
	::msgcat::mcset it_it  "Add %s" "Aggiungi %s"
	::msgcat::mcset it_it  "Add Block Comment"  "Aggiungi Blocco Commento"
	::msgcat::mcset it_it  "Add Task"  "Aggiungi Compito"
	::msgcat::mcset it_it  "Add Watch..." "Aggiungi Watch..."
	::msgcat::mcset it_it  "Adjust Tab Width" "Regola Larghezza Tab"
	::msgcat::mcset it_it  "Build ' %s ' ..." "Costruisci ' %s ' ..."
	::msgcat::mcset it_it  "Build ..." "Costruisci ..."
	::msgcat::mcset it_it  "Build Project..." "Costruisci Progetto..."
	::msgcat::mcset it_it  "Close"  "Chiudi"
	::msgcat::mcset it_it  "Close All"  "Chiudi Tutto"
	::msgcat::mcset it_it  "Close Project"  "Chiudi Progetto"
	::msgcat::mcset it_it  "Collapse Toolbar"  "Piega Barra degli Strumenti"
	::msgcat::mcset it_it  "Copy"  "Copia"
	::msgcat::mcset it_it  "Cut"  "Taglia"
	::msgcat::mcset it_it  "Debug" "Debug"
	::msgcat::mcset it_it  "Debug Default Script..." "Debug Default Script..."
	::msgcat::mcset it_it  "Debug level" "Livello di Debug"
	::msgcat::mcset it_it  "Debug..." "Debug..."
	::msgcat::mcset it_it  "Deep" "Accurato"
	::msgcat::mcset it_it  "Default Disabled"  "Disabilitato Come Predefinito"
	::msgcat::mcset it_it  "Default Enabled"  "Abilitato Come Predefinito"
	::msgcat::mcset it_it  "Default script not exists!" "Lo script predefinito non esiste!"
	::msgcat::mcset it_it  "Delete"  "Cancella"
	::msgcat::mcset it_it  "Delete ' %s '" "Cancella ' %s '"
	::msgcat::mcset it_it  "Delete Completed Tasks"  "Cancella Compiti Completati"
	::msgcat::mcset it_it  "Diabled All"  "Disabilita Tutto"
	::msgcat::mcset it_it  "Disabled Current Editor"  "Disabilita Editor Corrente"
	::msgcat::mcset it_it  "Edit"  "Modifica"
	::msgcat::mcset it_it  "Editor Details"  "Dettagli Editor"
	::msgcat::mcset it_it  "Enabled All"  "Abilita Tutto"
	::msgcat::mcset it_it  "Enabled Current Editor"  "Abilita Editor Corrente"
	::msgcat::mcset it_it  "Exit"  "Uscita"
	::msgcat::mcset it_it  "Expand Toolbar"  "Amplia Barra degli Strumenti"
	::msgcat::mcset it_it  "File"  "File"
	::msgcat::mcset it_it  "File Relation"  "Rapporto File"
	::msgcat::mcset it_it  "Find/Replace..."  "Trova/Sostituisci..."
	::msgcat::mcset it_it  "Folder..."  "Cartella..."
	::msgcat::mcset it_it  "Free Go" "Free Go"
	::msgcat::mcset it_it  "Help"  "Aiuto"
	::msgcat::mcset it_it  "Import..."  "Importa..."
	::msgcat::mcset it_it  "Indent Selection"  "Indenta Selezione"
	::msgcat::mcset it_it  "Insert Macro"  "Inserisci Macro"
	::msgcat::mcset it_it  "Jump To..."  "Salta A..."
	::msgcat::mcset it_it  "Language"  "Lingua"
	::msgcat::mcset it_it  "Locale"  "Locale"
	::msgcat::mcset it_it  "MP3 Directory - %s" "MP3 Directory - %s"
	::msgcat::mcset it_it  "MP3 Player Details"  "Dettagli Player MP3"
	::msgcat::mcset it_it  "New"  "Nuovo"
	::msgcat::mcset it_it  "Next Page"  "Pagina Successiva"
	::msgcat::mcset it_it  "Normal" "Normale"
	::msgcat::mcset it_it  "Open"  "Apri"
	::msgcat::mcset it_it  "Open File"  "Apri File"
	::msgcat::mcset it_it  "Open File..."  "Apri File..."
	::msgcat::mcset it_it  "Open Project..."  "Apri Progetto..."
	::msgcat::mcset it_it  "Options"  "Opzioni"
	::msgcat::mcset it_it  "Paste"  "Incolla"
	::msgcat::mcset it_it  "Pause" "Pausa"
	::msgcat::mcset it_it  "Previous Page"  "Pagina Precedente"
	::msgcat::mcset it_it  "Print..."  "Stampa..."
	::msgcat::mcset it_it  "Printer Setup*"  "Imposta Stampante*"
	::msgcat::mcset it_it  "Proc Details"  "Dettaglio Procedure"
	::msgcat::mcset it_it  "Project"  "Progetto"
	::msgcat::mcset it_it  "Project..."  "Progetto..."
	::msgcat::mcset it_it  "Properties..."  "Proprietà..."
	::msgcat::mcset it_it  "Raise"  "Seleziona"
	::msgcat::mcset it_it  "Recent Files"  "Files Recenti"
	::msgcat::mcset it_it  "Recent Projects"  "Progetti Recenti"
	::msgcat::mcset it_it  "Redo"  "Ripeti"
	::msgcat::mcset it_it  "Refresh"  "Aggiorna"
	::msgcat::mcset it_it  "Refresh Interval (%s ms)" "Intervallo di aggiornamento (%s ms)"
	::msgcat::mcset it_it  "Remove Block Comment"  "Rimuovi Blocco Commento"
	::msgcat::mcset it_it  "Run Default Script..." "Esegui Script Predefinito..."
	::msgcat::mcset it_it  "Run..."  "Esegui..."
	::msgcat::mcset it_it  "Save"  "Salva"
	::msgcat::mcset it_it  "Save All"  "Salva Tutto"
	::msgcat::mcset it_it  "Save As"  "Salva Come"
	::msgcat::mcset it_it  "Save As ..."  "Salva Come ..."
	::msgcat::mcset it_it  "Save Macro"  "Salva Macro"
	::msgcat::mcset it_it  "Search Files..."  "Cerca Files..."
	::msgcat::mcset it_it  "Search In Files..."  "Cerca Nei Files..."
	::msgcat::mcset it_it  "Select All"  "Seleziona Tutto"
	::msgcat::mcset it_it  "Set ' %s ' As Default Script" "Imposta ' %s ' Come Script Predefinito"
	::msgcat::mcset it_it  "Settings..."  "Impostazioni..."
	::msgcat::mcset it_it  "Shallow" "Superficiale"
	::msgcat::mcset it_it  "Show Line Number"  "Mostra Numero Linea"
	::msgcat::mcset it_it  "Show Syntax Helper" "Visualizza Aiutante di Sintassi"
	::msgcat::mcset it_it  "Step" "Fase"
	::msgcat::mcset it_it  "Stop" "Ferma"
	::msgcat::mcset it_it  "Syntax Check..." "Controllo Sintassi..."
	::msgcat::mcset it_it  "Syntax Highlight"  "Evidenzia Sintassi"
	::msgcat::mcset it_it  "Tasks"  "Compiti"
	# New
	::msgcat::mcset it_it  "Test" "Testa"
	::msgcat::mcset it_it  "Test(W)"  "Testa(W)"
	::msgcat::mcset it_it  "The settings will apply at restart CrowTDE!"  "Le impostazioni verranno applicate al riavvio di CrowTDE!"
	::msgcat::mcset it_it  "Toolbar Details"  "Dettagli Barra degli Strumenti"
	::msgcat::mcset it_it  "Tools(T)"  "Strumenti(T)"
	::msgcat::mcset it_it  "UnIndent Selection"  "DeIndenta Selezione"
	::msgcat::mcset it_it  "Undo"  "Annulla"
	::msgcat::mcset it_it  "Version Control*"  "Version Control*"
	::msgcat::mcset it_it  "Window"  "Finestra"
	::msgcat::mcset it_it  "error!" "errore!"
	# New
	::msgcat::mcset it_it  "freewrap*" "freewrap*"
}

namespace eval ::fmeNagelfar {
	::msgcat::mcset it_it  "Choose File" "Scegli File"
	::msgcat::mcset it_it  "Clear" "Pulisci"
	::msgcat::mcset it_it  "Do Check" "Controlla"
	::msgcat::mcset it_it  "File:" "File:"
	::msgcat::mcset it_it  "Save" "Salva"
	::msgcat::mcset it_it  "Save Output..." "Salva Risultato..."
	# New
	::msgcat::mcset it_it  "Select File" "Seleziona File"
	::msgcat::mcset it_it  "Select File..." "Seleziona File..."
}

namespace eval ::fmePlayer {
	::msgcat::mcset it_it  "MP3 Folder"  "Cartella MP3"
	::msgcat::mcset it_it  "MP3:"  "MP3:"
	::msgcat::mcset it_it  "Vol:"  "Vol:"
}

namespace eval ::fmeProcManager {
	::msgcat::mcset it_it  "Error" "Error"
	::msgcat::mcset it_it  "Interval"  "Intervallo"
	::msgcat::mcset it_it  "Please specify Tcl interpreter first!" "Please specify Tcl interpreter first!"
	::msgcat::mcset it_it  "View"  "Visualizza"
}

namespace eval ::fmeProjectManager {
	::msgcat::mcset it_it  "%s Open" "%s Aperto"
	::msgcat::mcset it_it  "'%s' already exists!" "'%s' esiste già!"
	::msgcat::mcset it_it  "'%s' already exists." "'%s' esiste già."
	::msgcat::mcset it_it  "'%s' has been deleted from the file system!" "'%s' è stato cancellato dal file system!"
	::msgcat::mcset it_it  "'%s' not exists!" "'%s' non esiste!"
	::msgcat::mcset it_it  "All"  "Tutto"
	::msgcat::mcset it_it  "Are you sure you want to delete '%s' from the file system ?" "Sei sicuro di voler cancellare '%s' dal file system ?"
	::msgcat::mcset it_it  "Build..." "Build..."
	::msgcat::mcset it_it  "Cancel" "Cancella"
	::msgcat::mcset it_it  "Check Syntax*"  "Controlla Sintassi*"
	::msgcat::mcset it_it  "Close Project"  "Chiudi Progetto"
	::msgcat::mcset it_it  "Confirm"  "Conferma"
	::msgcat::mcset it_it  "Copied %s" "Copiato %s"
	::msgcat::mcset it_it  "Copy"  "Copia"
	::msgcat::mcset it_it  "Cut"  "Taglia"
	::msgcat::mcset it_it  "Cut %s" "Taglia %s"
	::msgcat::mcset it_it  "Debug..." "Debug..."
	::msgcat::mcset it_it  "Default script not exists" "Lo script predefinito non esiste"
	::msgcat::mcset it_it  "Default script not specify!"  "Lo script predefinito non specificato!"
	::msgcat::mcset it_it  "Delete"  "Cancella"
	::msgcat::mcset it_it  "Edit"  "Modifica"
	::msgcat::mcset it_it  "Error"  "Errore"
	::msgcat::mcset it_it  "File Properties..."  "Proprietà File..."
	::msgcat::mcset it_it  "File copy fail!"  "Copia file fallita!"
	::msgcat::mcset it_it  "File name invalid." "Nome file non valido."
	::msgcat::mcset it_it  "Folder"  "Cartella"
	::msgcat::mcset it_it  "Folder already exists!"  "La cartella esiste già!"
	::msgcat::mcset it_it  "Import to : (%s)" "Importa da : (%s)"
	::msgcat::mcset it_it  "Location : %s" "Location : %s"
	::msgcat::mcset it_it  "New Folder"  "Nuova Cartella"
	::msgcat::mcset it_it  "New Item"  "Nuovo Elemento"
	::msgcat::mcset it_it  "No copy target"  "Nessuna destinazione per la copia"
	::msgcat::mcset it_it  "Ok" "Ok"
	::msgcat::mcset it_it  "Open" "Apri"
	::msgcat::mcset it_it  "Open As..."  "Apri Come..."
	::msgcat::mcset it_it  "Open Project"  "Apri Progetto"
	::msgcat::mcset it_it  "Others..."  "Altri..."
	::msgcat::mcset it_it  "Paste"  "Incolla"
	::msgcat::mcset it_it  "Please specify Tcl or Tk interpreter first!" "Per favore specifica prima un interprete Tcl o Tk!"
	::msgcat::mcset it_it  "Project - %s" "Progetto - %s"
	::msgcat::mcset it_it  "Project Properties..."  "Proprietà Progetto..."
	::msgcat::mcset it_it  "Rename"  "Rinomina"
	::msgcat::mcset it_it  "Rename fail!"  "Rinominazione fallita!"
	::msgcat::mcset it_it  "Replace" "Sostituisci"
	::msgcat::mcset it_it  "Run..."  "Esegui..."
	::msgcat::mcset it_it  "Save Project.."  "Salva Progetto.."
	::msgcat::mcset it_it  "Set As Default Script"  "Imposta Come Script Predefinito"
	::msgcat::mcset it_it  "Syntax Check..." "Controllo Sintassi..."
	::msgcat::mcset it_it  "The folder already contains a file named %s" "La cartella contiene già un file di nome %s"
	::msgcat::mcset it_it  "The operation need close current project. Close project ?"  "L'operazione richiede la chiusura del progetto corrente. Chiudere il progetto ?"
	::msgcat::mcset it_it  "refresh"  "aggiorna"
}

namespace eval ::fmeStatusBar {
	::msgcat::mcset it_it  "Lines"  "Linee"
	::msgcat::mcset it_it  "Pos"  "Posizione"
}

namespace eval ::fmeTabEditor {
	::msgcat::mcset it_it  "'%s' has not save. save it ?" "'%s' non è stato salvato. salvarlo ?"
	::msgcat::mcset it_it  "Cancal"  "Cancella"
	::msgcat::mcset it_it  "Copy %s - %s" "Copia %s - %s"
	::msgcat::mcset it_it  "Cut %s - %s" "Taglia %s - %s"
	::msgcat::mcset it_it  "No Copy Region"  "No Copy Region"
	::msgcat::mcset it_it  "No Cut Region"  "No Cut Region"
	::msgcat::mcset it_it  "Paste"  "Incolla"
	::msgcat::mcset it_it  "Print"  "Stampa"
	::msgcat::mcset it_it  "Print Command:"  "Comando Di Stampa:"
}

namespace eval ::fmeTabMgr {
	::msgcat::mcset it_it  "Debug" "Debug"
	::msgcat::mcset it_it  "File"  "File"
	::msgcat::mcset it_it  "Help" "Aiuto"
	::msgcat::mcset it_it  "Proc"  "Proc"
}

namespace eval ::fmeTask {
	::msgcat::mcset it_it  "Add Task"  "Aggiungi Compito"
	::msgcat::mcset it_it  "All" "Tutto"
	::msgcat::mcset it_it  "Are you sure you want to delete %%d tasks?" "Sei sicuro di voler cancellare i compiti %%d?"
	::msgcat::mcset it_it  "Change State" "Cambia Stato"
	::msgcat::mcset it_it  "Delete"  "Cancella"
	::msgcat::mcset it_it  "Delete Completed Tasks"  "Cancella Compiti Completati"
	::msgcat::mcset it_it  "Delete Task"  "Cancella Compito"
	::msgcat::mcset it_it  "Description"  "Descrizione"
	::msgcat::mcset it_it  "Do you want to delete completed task ?"  "Sei sicuro di cancellare i compiti completati ?"
	::msgcat::mcset it_it  "Do you want to delete task ?"  "Sei sicuro di voler cancellare il compito ?"
	::msgcat::mcset it_it  "Edit"  "Modifica"
	::msgcat::mcset it_it  "Find" "Cerca"
	::msgcat::mcset it_it  "Finished" "Finiti"
	::msgcat::mcset it_it  "Hide Completed Tasks" "Nascondi Compiti Completati"
	::msgcat::mcset it_it  "In Progress" "In Corso"
	::msgcat::mcset it_it  "Not Started" "Not Avviato"
	::msgcat::mcset it_it  "Refresh"  "Aggiorna"
	::msgcat::mcset it_it  "Reset" "Riavvia"
	::msgcat::mcset it_it  "Search:" "Search:"
	::msgcat::mcset it_it  "State"  "Stato"
	::msgcat::mcset it_it  "Task Delete"  "Cancella Compito"
	::msgcat::mcset it_it  "Task already hidden!" "Compito già nascosto!"
	::msgcat::mcset it_it  "Time"  "Tempo"
}

namespace eval ::fmeTaskMgr {
	::msgcat::mcset it_it  "Debug" "Debug"
	::msgcat::mcset it_it  "Nagelfar" "Nagelfar"
	::msgcat::mcset it_it  "Tasks"  "Compiti"
	::msgcat::mcset it_it  "TkCon"  "TkCon"
}

namespace eval ::fmeToolbar {
	::msgcat::mcset it_it  "Add Block Comment"  "Aggiungi Blocco Commento"
	::msgcat::mcset it_it  "Backward"  "All'indietro"
	::msgcat::mcset it_it  "Case Sensitive"  "Rispetta Maiuscole/Minuscole"
	::msgcat::mcset it_it  "Copy"  "Copia"
	::msgcat::mcset it_it  "Cut"  "Taglia"
	::msgcat::mcset it_it  "Debug Default Script..." "Debug Default Script..."
	# New
	::msgcat::mcset it_it  "Debug current file" "Debug current file"
	# New
	::msgcat::mcset it_it  "Debug project" "Debug project"
	::msgcat::mcset it_it  "Debug..." "Debug..."
	::msgcat::mcset it_it  "File..."  "File..."
	::msgcat::mcset it_it  "Find"  "Ricerca"
	::msgcat::mcset it_it  "Find Options"  "Opzioni di Ricerca"
	::msgcat::mcset it_it  "Folder..."  "Cartella..."
	::msgcat::mcset it_it  "Ident Selection"  "Identa Selezione"
	::msgcat::mcset it_it  "MP3 Player" "MP3 Player"
	::msgcat::mcset it_it  "New"  "Nuovo"
	::msgcat::mcset it_it  "Open"  "Apri"
	::msgcat::mcset it_it  "Open File"  "Apri File"
	::msgcat::mcset it_it  "Paste"  "Incolla"
	::msgcat::mcset it_it  "Print current editor..." "Stampa editor corrente..."
	::msgcat::mcset it_it  "Project..."  "Progetto..."
	::msgcat::mcset it_it  "Redo"  "Ripeti"
	::msgcat::mcset it_it  "Regular Expression"  "Espressioni Regolari"
	::msgcat::mcset it_it  "Remove Block Comment"  "Rimuovi Blocco Commento"
	::msgcat::mcset it_it  "Run Project..."  "Esegui Progetto..."
	::msgcat::mcset it_it  "Run..."  "Esegui..."
	::msgcat::mcset it_it  "Save"  "Salva"
	::msgcat::mcset it_it  "Save All"  "Salva Tutto"
	::msgcat::mcset it_it  "Search files" "Cerca files"
	::msgcat::mcset it_it  "Search in files" "Cerca nei files"
	::msgcat::mcset it_it  "Start Debugger" "Avvia Debugger"
	::msgcat::mcset it_it  "Stop" "Ferma"
	::msgcat::mcset it_it  "Stop '%s'" "Ferma '%s'"
	::msgcat::mcset it_it  "Syntax check..." "Controllo sintassi..."
	::msgcat::mcset it_it  "UnIdent Selection"  "DeIdenta Selezione"
	::msgcat::mcset it_it  "Undo"  "Annulla"
}

namespace eval ::frmAbout {
	::msgcat::mcset it_it  "About CrowTDE"  "Riguardo a CrowTDE"
	# New
	::msgcat::mcset it_it  "Copyright (C) 2006-2007 Tai, Yuan-Liang & Zheng, Shao-Huan" "Copyright (C) 2006-2007 Tai, Yuan-Liang & Zheng, Shao-Huan"
	::msgcat::mcset it_it  "Credits" "Crediti"
	::msgcat::mcset it_it  "CrowTDE License" "Licenza CrowTDE"
	::msgcat::mcset it_it  "CrowTDE is an open source Tcl/Tk development %s environment written in Tcl/Tk. Its purposes is to provide a %s convenient environment for Tcl/Tk programmers." "CrowTDE è un ambiente %s di sviluppo Tcl/Tk open source scritto in Tcl/Tk. I suoi obiettivi sono di offrire un %s comodo ambiente di sviluppo per i programmatori Tcl/Tk."
	::msgcat::mcset it_it  "Exit" "Uscita"
	::msgcat::mcset it_it  "German - Michael Schlenker <mic42@user.sourceforge.net> %s" "Tedesco - Michael Schlenker <mic42@user.sourceforge.net> %s"
	# New
	::msgcat::mcset it_it  "Italian - Diego <siarodx@gmail.com> %s" "Italiano - Diego <siarodx@gmail.com> %s"
	::msgcat::mcset it_it  "License" "Licenza"
	::msgcat::mcset it_it  "License:" "Licenza:"
	::msgcat::mcset it_it  "Traditional Chinese - Zang, Ke-Yuan <jarry@crow.ee.stut.edu.tw> %s" "Cinese Tradizionale - Zang, Ke-Yuan <jarry@crow.ee.stut.edu.tw> %s"
	::msgcat::mcset it_it  "Translators" "Traduttori"
	::msgcat::mcset it_it  "Visit : http://crow.ee.stut.edu.tw/dai/crowtde/" "Visita : http://crow.ee.stut.edu.tw/dai/crowtde/"
}

namespace eval ::frmCheckSave {
	::msgcat::mcset it_it  "Cancel"  "Cancella"
	::msgcat::mcset it_it  "No"  "No"
	::msgcat::mcset it_it  "Save"  "Salva"
	::msgcat::mcset it_it  "Save files ?" "Salvare files ?"
	::msgcat::mcset it_it  "Yes"  "Si"
}

namespace eval ::frmFirst {
	::msgcat::mcset it_it  "Basic Settings"  "Impostazioni Semplici"
	::msgcat::mcset it_it  "Browse..."  "Sfoglia..."
	::msgcat::mcset it_it  "Information"  "Informazioni"
	::msgcat::mcset it_it  "Language:"  "Lingua:"
	::msgcat::mcset it_it  "Ok"  "Ok"
	::msgcat::mcset it_it  "Open File"  "Apri File"
	::msgcat::mcset it_it  "Tcl Interpreter:"  "Interprete Tcl:"
	::msgcat::mcset it_it  "Tk Interpreter:"  "Interprete Tk:"
	::msgcat::mcset it_it  "You are first time running CrowTDE.%s Please configure your basic run-time environment." "Stai eseguendo CrowTDE per la prima volta.%s Per favore configura l'essenziale per l'avvio dell'ambiente."
	::msgcat::mcset it_it  "You can configure more details from 'Main Menu->Options->Settings' ."  "Puoi configurare più dettagli da 'Menu Principale->Opzioni->Impostazioni' ."
}

namespace eval ::frmNewProject {
	::msgcat::mcset it_it  "'%s' already exists." "'%s' esiste già."
	::msgcat::mcset it_it  "Browse..."  "Sfoglia..."
	::msgcat::mcset it_it  "Cancel"  "Cancella"
	::msgcat::mcset it_it  "Create"  "Crea"
	::msgcat::mcset it_it  "Default Script:"  "Script Predefinito:"
	::msgcat::mcset it_it  "Error"  "Errore"
	::msgcat::mcset it_it  "Interpreter"  "Interprete"
	::msgcat::mcset it_it  "Interpreter:"  "Interprete:"
	::msgcat::mcset it_it  "New Project"  "Nuovo Progetto"
	::msgcat::mcset it_it  "Please choose template first!"  "Per favore scegli prima un modello!"
	::msgcat::mcset it_it  "Project Name:"  "Nome Progetto:"
	::msgcat::mcset it_it  "Template:"  "Modello:"
	::msgcat::mcset it_it  "Workspace"  "Area di lavoro"
	::msgcat::mcset it_it  "Workspace:"  "Area di lavoro:"
}

namespace eval ::frmProjectProperty {
	::msgcat::mcset it_it  "Browse..."  "Sfoglia..."
	::msgcat::mcset it_it  "Cancel"  "Cancella"
	::msgcat::mcset it_it  "Default Script:"  "Script Predefinito:"
	::msgcat::mcset it_it  "Interpreter"  "Interprete"
	::msgcat::mcset it_it  "Interpreter:"  "Interprete:"
	::msgcat::mcset it_it  "Ok"  "Ok"
	::msgcat::mcset it_it  "Project Name:"  "Nome Progetto:"
	::msgcat::mcset it_it  "Project Properties"  "Proprietà Progetto"
	::msgcat::mcset it_it  "Workspace:"  "Area di lavoro:"
}

namespace eval ::frmSearchFiles {
	::msgcat::mcset it_it  "Browse..."  "Sfoglia..."
	::msgcat::mcset it_it  "Choose Directory"  "Scegli Cartella"
	::msgcat::mcset it_it  "Directory:"  "Cartella:"
	::msgcat::mcset it_it  "Error"  "Errore"
	::msgcat::mcset it_it  "File name:"  "Nome file:"
	::msgcat::mcset it_it  "Finish %s items found." "Finito %s oggetti trovati."
	::msgcat::mcset it_it  "Keyword can't empty!"  "La parola chiave non può essere vuota!"
	::msgcat::mcset it_it  "Search directory not valid!"  "Cartella di ricerca non valida!"
	::msgcat::mcset it_it  "Search files" "Cerca files"
	::msgcat::mcset it_it  "Search hidden files & folders"  "Cerca files e cartelle nascoste"
	::msgcat::mcset it_it  "Start"  "Avvia"
	::msgcat::mcset it_it  "Stop"  "Ferma"
}

namespace eval ::frmSearchInFiles {
	::msgcat::mcset it_it  "Browse..."  "Sfoglia..."
	::msgcat::mcset it_it  "Case Sensitive"  "Rispetta Maiuscole/Minuscole"
	::msgcat::mcset it_it  "Choose Directory"  "Scegli Cartella"
	::msgcat::mcset it_it  "Directory"  "Cartella"
	::msgcat::mcset it_it  "Error"  "Errore"
	::msgcat::mcset it_it  "Filter:"  "Filtro:"
	::msgcat::mcset it_it  "Keyword can't empty!"  "La parola chiave non può essere vuota!"
	::msgcat::mcset it_it  "Keyword:"  "Parola chiave:"
	::msgcat::mcset it_it  "Regular Expression"  "Espressione Regolare"
	::msgcat::mcset it_it  "Search directory not valid!"  "Cartella di ricerca non valida!"
	::msgcat::mcset it_it  "Search hidden files & folders"  "Cerca files e cartelle nascoste"
	::msgcat::mcset it_it  "Search in files" "Cerca nei files"
	::msgcat::mcset it_it  "Start"  "Avvia"
	::msgcat::mcset it_it  "Stop"  "Ferma"
}

namespace eval ::frmSetting {
	::msgcat::mcset it_it  "CrowTDE configuration" "Configurazione CrowTDE"
	::msgcat::mcset it_it  "Editor Settings" "Impostazioni Editor"
	::msgcat::mcset it_it  "Exit"  "Uscita"
	::msgcat::mcset it_it  "File Settings" "Impostazioni File"
	::msgcat::mcset it_it  "Fonts"  "Fonts"
	::msgcat::mcset it_it  "General"  "Generale"
}

namespace eval ::frmStartPage {
	::msgcat::mcset it_it  "Browse..."  "Sfoglia..."
	::msgcat::mcset it_it  "Cancel"  "Cancella"
	::msgcat::mcset it_it  "Create New Project..."  "Crea Nuovo Progetto..."
	::msgcat::mcset it_it  "CrowTDE Start Page"  "Pagina Iniziale CrowTDE"
	::msgcat::mcset it_it  "Ok"  "Ok"
	::msgcat::mcset it_it  "Open Last Project (%s)" "Apri Ultimo Progetto (%s)"
	::msgcat::mcset it_it  "Open Project"  "Apri Progetto"
	::msgcat::mcset it_it  "Please Choose Function"  "Per favore scegli una funzione"
	::msgcat::mcset it_it  "Project:"  "Progetto:"
}

namespace eval ::svnWrapper {
	# New
	::msgcat::mcset it_it  "...ok!" "...ok!"
	# New
	::msgcat::mcset it_it  "Add" "Aggiungi"
	# New
	::msgcat::mcset it_it  "Are you want to remove '%s' propeties?" "Vuoi rimuovere  '%s' proprietà?"
	# New
	::msgcat::mcset it_it  "Cancel" "Annulla"
	# New
	::msgcat::mcset it_it  "Check for modifications" "Controlla modifiche"
	# New
	::msgcat::mcset it_it  "Checkout" "Preleva"
	# New
	::msgcat::mcset it_it  "Checkout directory:" "Preleva cartella:"
	# New
	::msgcat::mcset it_it  "Checkout from SVN" "Preleva da SVN"
	# New
	::msgcat::mcset it_it  "Choose Directory" "Scegli cartella"
	# New
	::msgcat::mcset it_it  "Clean up" "Pulisci"
	# New
	::msgcat::mcset it_it  "Commit" "Applica"
	# New
	::msgcat::mcset it_it  "Commit to : %s" "Applica a : %s"
	# New
	::msgcat::mcset it_it  "Delete" "Cancella"
	# New
	::msgcat::mcset it_it  "Directory can't empty." "La cartella non può essere vuota."
	# New
	::msgcat::mcset it_it  "Directory:" "Cartella:"
	# New
	::msgcat::mcset it_it  "Edit" "Modifica"
	# New
	::msgcat::mcset it_it  "Error!" "Errore!"
	# New
	::msgcat::mcset it_it  "Export" "Esporta"
	# New
	::msgcat::mcset it_it  "Export: %s" "Esporta: %s"
	# New
	::msgcat::mcset it_it  "File list is empty!" "La lista file è vuota!"
	# New
	::msgcat::mcset it_it  "HEAD revision" "Revisione principale"
	# New
	::msgcat::mcset it_it  "Import" "Importa"
	# New
	::msgcat::mcset it_it  "Import Message:" "Importa Messaggio:"
	# New
	::msgcat::mcset it_it  "Include ignored files" "Includi files ignorati"
	# New
	::msgcat::mcset it_it  "Include unversion file(s)" "Includi file(s) senza versione"
	# New
	::msgcat::mcset it_it  "Login" "Login"
	# New
	::msgcat::mcset it_it  "Message : " "Messaggio : "
	# New
	::msgcat::mcset it_it  "Move" "Muovi"
	# New
	::msgcat::mcset it_it  "Move to:" "Muovi su:"
	# New
	::msgcat::mcset it_it  "No files were changed or added since the last commit." "Nessun files è cambiato o aggiunto dall'ultima applicazione."
	# New
	::msgcat::mcset it_it  "Not thing to do." "Nulla da compiere."
	# New
	::msgcat::mcset it_it  "Ok" "Ok"
	# New
	::msgcat::mcset it_it  "Passwd:" "Passwd:"
	# New
	::msgcat::mcset it_it  "Please select a property first!" "Per favore seleziona prima una proprietà!"
	# New
	::msgcat::mcset it_it  "Please wait" "Attendi per favore"
	# New
	::msgcat::mcset it_it  "Properties" "Proprietà"
	# New
	::msgcat::mcset it_it  "Property" "Proprietà"
	# New
	::msgcat::mcset it_it  "Property :" "Proprietà :"
	# New
	::msgcat::mcset it_it  "Remove" "Rimuovi"
	# New
	::msgcat::mcset it_it  "Remove properties" "Rimuovi proprietà"
	# New
	::msgcat::mcset it_it  "Rename" "Rinomina"
	# New
	::msgcat::mcset it_it  "Repository:" "Deposito:"
	# New
	::msgcat::mcset it_it  "Resolved" "Risolto"
	# New
	::msgcat::mcset it_it  "Revert" "Torna a prima"
	# New
	::msgcat::mcset it_it  "Revision" "Revisione"
	# New
	::msgcat::mcset it_it  "SVN Update" "Aggiorna SVN"
	# New
	::msgcat::mcset it_it  "Status" "Stato"
	# New
	::msgcat::mcset it_it  "Subversion" "Subversion"
	# New
	::msgcat::mcset it_it  "Svn" "Svn"
	# New
	::msgcat::mcset it_it  "Target : %s" "Obiettivo : %s"
	# New
	::msgcat::mcset it_it  "URL can't empty." "L'URL non può essere vuoto."
	# New
	::msgcat::mcset it_it  "URL of repository:" "URL del deposito:"
	# New
	::msgcat::mcset it_it  "Update" "Aggiorna"
	# New
	::msgcat::mcset it_it  "Username:" "Nome utente:"
	# New
	::msgcat::mcset it_it  "Value" "Valore"
	# New
	::msgcat::mcset it_it  "Value :" "Valore :"
	# New
	::msgcat::mcset it_it  "error" "errore"
	# New
	::msgcat::mcset it_it  "update" "aggiorna"
}

namespace eval ::crowTemplate {
	#New
	::msgcat::mcset zh_tw "Empty file" "File vuoto"
	#New
	::msgcat::mcset zh_tw "Tcl Package" "Pacchetto Tcl"
	
	#New
	::msgcat::mcset zh_tw "Create an empty project." "Crea progetto vuoto."	
	# New
	::msgcat::mcset zh_tw  "Checkout project from SVN Repository." "Preleva progetto da un deposito SVN."
	# New
	::msgcat::mcset zh_tw  "SVN Project" "Progetto SVN"
}