# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

if {![namespace exists ::tw]} {
	namespace eval ::tw {
		variable OPTS
		array set OPTS [list version 1.0]
		
		variable OBJ
		array set OBJ [list]
	}
	set ::tw::OPTS(pkgDir) $dir
	set f [file join $dir locales [::msgcat::mclocale].msg]
	if {[file exists $f]} {
			namespace eval :: [list source -encoding utf-8 $f]
	}
	source -encoding utf-8 [file join $dir binds.tcl]
}
package ifneeded ::tw::ibox $::tw::OPTS(version) [list source [file join $dir ibox.tcl]]
package ifneeded ::tw::rc $::tw::OPTS(version) [list source [file join $dir rc.tcl]]
package ifneeded ::tw::dialog $::tw::OPTS(version) [list source [file join $dir dialog.tcl]]
package ifneeded ::tw::treeview $::tw::OPTS(version) [list source [file join $dir treeview.tcl]]
package ifneeded ::tw::toolbar $::tw::OPTS(version) [list source [file join $dir toolbar.tcl]]

