# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded crowSyntax 1.0 [list source [file join $dir crowSyntax.tcl]]
package ifneeded crowEditor 1.0 [list source [file join $dir crowEditor.tcl]]
package ifneeded crowFileRelation 1.0 [list source [file join $dir crowFileRelation.tcl]]
package ifneeded crowFileProperties 1.0 [list source [file join $dir crowFileProperties.tcl]]
package ifneeded crowFontConf 1.0 [list source [file join $dir crowFontConf.tcl]]
package ifneeded crowFont 1.0 [list source [file join $dir crowFont.tcl]]
package ifneeded crowIO 1.0 [list source [file join $dir crowIO.tcl]]
package ifneeded crowImg 1.0 [list source [file join $dir crowImg.tcl]]
package ifneeded crowGetDir 1.0 [list source [file join $dir crowGetDir.tcl]]
package ifneeded crowMacro 1.0 [list source [file join $dir crowMacro.tcl]]
package ifneeded crowNoteBook 1.0 [list source [file join $dir crowNoteBook.tcl]]
package ifneeded crowRecently 1.0 [list source [file join $dir crowRecently.tcl]]
package ifneeded crowThread 1.0 [list source [file join $dir crowThread.tcl]]
package ifneeded crowExec 1.0 [list source [file join $dir crowExec.tcl]]
package ifneeded inputDlg 1.0 [list source [file join $dir inputDlg.tcl]]
package ifneeded crowRC 1.0 [list source [file join $dir crowRC.tcl]]
package ifneeded recently 1.0 [list source [file join $dir recently.tcl]]
package ifneeded crowPanedWindow 1.0 [list source [file join $dir crowPanedWindow.tcl]]
package ifneeded crowHighlight 1.0 [list source [file join $dir crowHighlight.tcl]]
package ifneeded crowTemplate 1.0 [list source [file join $dir crowTemplate.tcl]]
package ifneeded Tclparser 1.0 [list source [file join $dir Tclparser.tcl]]
package ifneeded crowSdx 1.0 [list source [file join $dir crowSdx.tcl]]
package ifneeded crowDebugger 1.0 [list source [file join $dir crowDebugger.tcl]]
