# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded ttdialog 1.0 [list source [file join $dir ttdialog.tcl]]
package ifneeded ttrc 1.0 [list source [file join $dir ttrc.tcl]]
package ifneeded ttimgr 1.0 [list source [file join $dir ttimgr.tcl]]
package ifneeded gvfs 1.0 [list source [file join $dir gvfs.tcl]]
package ifneeded imap 1.0 [list source [file join $dir imap.tcl]]
package ifneeded smtp 1.0 [list source [file join $dir smtp.tcl]]
package ifneeded toolbar 1.0 [list source [file join $dir toolbar.tcl]]
package ifneeded tooltip 1.4.2 [list source [file join $dir tooltip-1.4.2.tcl]]
package ifneeded gutil 1.0 [list source [file join $dir gutil.tcl]]
